/*jslint-disable*/
// Copyright (c) 2021 Kai Zhu
// SPDX-License-Identifier: MIT
// 2022-07-15T17:46:01+0000
(function () {
"use strict";

var f;f||(f=typeof Module !== 'undefined' ? Module : {});var ba=Object.assign;(function(){function a(){}function b(...c){a("\n\ndebugInline");a(...c);a("\n");return c[0]}b();a=console.error;return b})();
(async function(){function a(k){let l=k.argList,n=new Uint8Array(k.baton&&k.baton.buffer);var p=0;let t=k.cFuncName,u=l[4];var D=p=0;let aa="",Jb=k.id;D=l[2];switch(t){case "_dbClose":case "_dbExec":case "_dbFileImportOrExport":case "_dbNoop":case "_dbOpen":p=ca(n.byteLength);k.batonPtr=p;h.set(n,p);switch(t){case "_dbClose":k=d(p,1);console.error(`_dbClose("${k}")`);break;case "_dbFileImportOrExport":D||da(new Uint8Array(u));break;case "_dbOpen":k=d(p,0),console.error(`_dbOpen("${k}")`)}f[t](p);
aa=c(p);n.set(new Uint8Array(h.buffer,h.byteOffset+p,1024));n=new BigInt64Array(n.buffer,8);n.subarray(16,32).forEach(function(E,F){l[F]&&(l[F].constructor===ArrayBuffer||"function"===typeof SharedArrayBuffer&&l[F].constructor===SharedArrayBuffer)||(E=Number(E),0===E?l[F]=n[F]:(l[F]=new ArrayBuffer(Number(n[F])),(new Uint8Array(l[F])).set(h.subarray(E,E+l[F].byteLength)),ea(E)))});switch(!aa&&t){case "_dbFileImportOrExport":D&&(u=fa(),l[4]=u.buffer);break;case "_dbOpen":u&&(da(new Uint8Array(u)),
p=Number(l[0]),(D=b(p,"/tmp/__dbtmp1",0))&&(aa=g(p)))}postMessage({argList:l,baton:new DataView(n.buffer),cFuncName:t,errmsg:aa,id:Jb},[n.buffer,...l.filter(function(E){return E&&E.constructor===ArrayBuffer})]);return}throw Error(`invalid cFuncName "${t}"`);}let b,c,d,e,g;globalThis.onmessage=async function({data:k}){let l=k.cFuncName;await e;k.batonPtr=0;try{await a(k)}catch(n){postMessage({errmsg:n.stack,id:k.id})}finally{switch(ea(k.batonPtr),l){case "_dbFileImportOrExport":case "_dbOpen":try{ha("/tmp/__dbtmp1")}catch(n){}}}};
e=new Promise(function(k){f.postRun=k});await e;b=m("__dbFileImportOrExport","number",["number","string","number"]);c=m("jsbatonValueErrmsg","string",["number"]);d=m("jsbatonValueStringArgi","string",["number","number"]);g=m("sqlite3_errmsg","string",["number"]);ia()})();var ja=ba({},f),ka="./this.program",la="object"===typeof window,q="function"===typeof importScripts,ma="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,r="",na,oa,pa,fs,qa,ra;
if(ma)r=q?require("path").dirname(r)+"/":__dirname+"/",ra=()=>{qa||(fs=require("fs"),qa=require("path"))},na=function(a,b){ra();a=qa.normalize(a);return fs.readFileSync(a,b?null:"utf8")},pa=a=>{a=na(a,!0);a.buffer||(a=new Uint8Array(a));return a},oa=(a,b,c)=>{ra();a=qa.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),f.inspect=function(){return"[Emscripten Module object]"};
else if(la||q)q?r=self.location.href:"undefined"!==typeof document&&document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):"",na=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(pa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),oa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var sa=f.print||console.log.bind(console),v=f.printErr||console.warn.bind(console);ba(f,ja);ja=null;f.thisProgram&&(ka=f.thisProgram);var w;f.wasmBinary&&(w=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&x("no native wasm support detected");var ta,ua=!1;
function va(a,b,c,d){var e={string:function(p){var t=0;if(null!==p&&void 0!==p&&0!==p){var u=(p.length<<2)+1;t=wa(u);y(p,h,t,u)}return t},array:function(p){var t=wa(p.length);z.set(p,t);return t}};a=f["_"+a];var g=[],k=0;if(d)for(var l=0;l<d.length;l++){var n=e[c[l]];n?(0===k&&(k=xa()),g[l]=n(d[l])):g[l]=d[l]}c=a.apply(null,g);return c=function(p){0!==k&&ya(k);return"string"===b?A(p):"boolean"===b?!!p:p}(c)}
function m(a,b,c,d){c=c||[];var e=c.every(function(g){return"number"===g});return"string"!==b&&e&&!d?f["_"+a]:function(){return va(a,b,c,arguments)}}var za="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function B(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&za)return za.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function A(a){return a?B(h,a,void 0):""}
function y(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var l=a.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function C(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Aa(a){var b=C(a)+1,c=Ba(b);c&&y(a,z,c,b);return c}var Ca,z,h,Da,G,Ea;
function Fa(){var a=ta.buffer;Ca=a;f.HEAP8=z=new Int8Array(a);f.HEAP16=Da=new Int16Array(a);f.HEAP32=G=new Int32Array(a);f.HEAPU8=h=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAPU32=new Uint32Array(a);f.HEAPF32=new Float32Array(a);f.HEAPF64=new Float64Array(a);f.HEAP64=Ea=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var Ga,Ha=[],Ia=[],Ja=[];function Ka(){var a=f.preRun.shift();Ha.unshift(a)}var H=0,La=null,I=null;f.preloadedImages={};f.preloadedAudios={};
function x(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";v(a);ua=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ma(){return J.startsWith("data:application/octet-stream;base64,")}var J;J="sqlmath_wasm.wasm";if(!Ma()){var Na=J;J=f.locateFile?f.locateFile(Na,r):r+Na}function Oa(){var a=J;try{if(a==J&&w)return new Uint8Array(w);if(pa)return pa(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function Pa(){if(!w&&(la||q)){if("function"===typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Oa()});if(oa)return new Promise(function(a,b){oa(J,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Oa()})}
function Qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Xa;"number"===typeof c?void 0===b.Ba?Ga.get(c)():Ga.get(c)(b.Ba):c(void 0===b.Ba?null:b.Ba)}}}function Ra(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}function Sa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function K(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sa(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Ta(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ua(a){if("/"===a)return"/";a=K(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Va(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ma)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){x("randomDevice")}}
function Wa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Sa(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Xa=[];function Ya(a,b){Xa[a]={input:[],output:[],wa:b};Za(a,$a)}
var $a={open:function(a){var b=Xa[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.wa.flush(a.tty)},flush:function(a){a.tty.wa.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.wa.Ja)throw new L(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.wa.Ja(a.tty)}catch(l){throw new L(29);}if(void 0===k&&0===e)throw new L(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.wa.Da)throw new L(60);
try{for(var e=0;e<d;e++)a.tty.wa.Da(a.tty,b[c+e])}catch(g){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},ab={Ja:function(a){if(!a.input.length){var b=null;if(ma){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(C(b)+1);b=y(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Da:function(a,b){null===b||10===b?(sa(B(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(sa(B(a.output,0)),a.output=[])}},bb={Da:function(a,b){null===b||10===b?(v(B(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(v(B(a.output,0)),a.output=[])}};
function cb(a){a=65536*Math.ceil(a/65536);var b=db(65536,a);if(!b)return 0;h.fill(0,b,b+a);return b}
var M={qa:null,ra:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.qa||(M.qa={dir:{node:{pa:M.ja.pa,oa:M.ja.oa,lookup:M.ja.lookup,xa:M.ja.xa,rename:M.ja.rename,unlink:M.ja.unlink,rmdir:M.ja.rmdir,readdir:M.ja.readdir,symlink:M.ja.symlink},stream:{ta:M.ka.ta}},file:{node:{pa:M.ja.pa,oa:M.ja.oa},stream:{ta:M.ka.ta,read:M.ka.read,write:M.ka.write,Fa:M.ka.Fa,ya:M.ka.ya,za:M.ka.za}},link:{node:{pa:M.ja.pa,oa:M.ja.oa,
readlink:M.ja.readlink},stream:{}},Ga:{node:{pa:M.ja.pa,oa:M.ja.oa},stream:eb}});c=fb(a,b,c,d);16384===(c.mode&61440)?(c.ja=M.qa.dir.node,c.ka=M.qa.dir.stream,c.la={}):32768===(c.mode&61440)?(c.ja=M.qa.file.node,c.ka=M.qa.file.stream,c.na=0,c.la=null):40960===(c.mode&61440)?(c.ja=M.qa.link.node,c.ka=M.qa.link.stream):8192===(c.mode&61440)&&(c.ja=M.qa.Ga.node,c.ka=M.qa.Ga.stream);c.timestamp=Date.now();a&&(a.la[b]=c,a.timestamp=c.timestamp);return c},Ya:function(a){return a.la?a.la.subarray?a.la.subarray(0,
a.na):new Uint8Array(a.la):new Uint8Array(0)},Ha:function(a,b){var c=a.la?a.la.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.la,a.la=new Uint8Array(b),0<a.na&&a.la.set(c.subarray(0,a.na),0))},Ua:function(a,b){if(a.na!=b)if(0==b)a.la=null,a.na=0;else{var c=a.la;a.la=new Uint8Array(b);c&&a.la.set(c.subarray(0,Math.min(b,a.na)));a.na=b}},ja:{pa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;
16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.na:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.La=4096;b.blocks=Math.ceil(b.size/b.La);return b},oa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.Ua(a,b.size)},lookup:function(){throw gb[44];},xa:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===
(a.mode&61440)){try{var d=N(b,c)}catch(g){}if(d)for(var e in d.la)throw new L(55);}delete a.parent.la[a.name];a.parent.timestamp=Date.now();a.name=c;b.la[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.la[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=N(a,b),d;for(d in c.la)throw new L(55);delete a.la[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.la)a.la.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,
b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},ka:{read:function(a,b,c,d,e){var g=a.node.la;if(e>=a.node.na)return 0;a=Math.min(a.node.na-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===z.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.la||a.la.subarray)){if(g)return a.la=b.subarray(c,c+d),a.na=d;if(0===a.na&&0===e)return a.la=
b.slice(c,c+d),a.na=d;if(e+d<=a.na)return a.la.set(b.subarray(c,c+d),e),d}M.Ha(a,e+d);if(a.la.subarray&&b.subarray)a.la.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.la[e+g]=b[c+g];a.na=Math.max(a.na,e+d);return d},ta:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.na);if(0>b)throw new L(28);return b},Fa:function(a,b,c){M.Ha(a.node,b+c);a.node.na=Math.max(a.node.na,b+c)},ya:function(a,b,c,d,e,g){if(0!==b)throw new L(28);if(32768!==(a.node.mode&61440))throw new L(43);
a=a.node.la;if(g&2||a.buffer!==Ca){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=cb(c);if(!c)throw new L(48);z.set(a,c)}else d=!1,c=a.byteOffset;return{Ta:c,Aa:d}},za:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.ka.write(a,b,0,d,c,!1);return 0}}},hb=null,ib={},O=[],jb=1,P=null,kb=!0,L=null,gb={},Q=(a,b={})=>{a=Wa("/",a);if(!a)return{path:"",node:null};var c={Ia:!0,Ea:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);
if(8<b.Ea)throw new L(32);a=Sa(a.split("/").filter(k=>!!k),!1);var e=hb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=N(e,a[d]);c=K(c+"/"+a[d]);e.ua&&(!g||g&&b.Ia)&&(e=e.ua.root);if(!g||b.sa)for(g=0;40960===(e.mode&61440);)if(e=lb(c),c=Wa(Ta(c),e),e=Q(c,{Ea:b.Ea}).node,40<g++)throw new L(32);}return{path:c,node:e}},mb=a=>{for(var b;;){if(a===a.parent)return a=a.ra.Ka,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},nb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=
(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%P.length},ob=a=>{var b=nb(a.parent.id,a.name);if(P[b]===a)P[b]=a.va;else for(b=P[b];b;){if(b.va===a){b.va=a.va;break}b=b.va}},N=(a,b)=>{var c;if(c=(c=R(a,"x"))?c:a.ja.lookup?0:2)throw new L(c,a);for(c=P[nb(a.id,b)];c;c=c.va){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ja.lookup(a,b)},fb=(a,b,c,d)=>{a=new pb(a,b,c,d);b=nb(a.parent.id,a.name);a.va=P[b];return P[b]=a},qb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},rb=a=>{var b=["r","w","rw"][a&
3];a&512&&(b+="w");return b},R=(a,b)=>{if(kb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},sb=(a,b)=>{try{return N(a,b),20}catch(c){}return R(a,"wx")},tb=(a,b,c)=>{try{var d=N(a,b)}catch(e){return e.ma}if(a=R(a,"wx"))return a;if(c){if(16384!==(d.mode&61440))return 54;if(d===d.parent||"/"===mb(d))return 10}else if(16384===(d.mode&61440))return 31;return 0},ub=(a=0,b=4096)=>{for(;a<=b;a++)if(!O[a])return a;
throw new L(33);},wb=(a,b)=>{vb||(vb=function(){},vb.prototype={});var c=new vb,d;for(d in a)c[d]=a[d];a=c;b=ub(b,void 0);a.fd=b;return O[b]=a},eb={open:a=>{a.ka=ib[a.node.rdev].ka;a.ka.open&&a.ka.open(a)},ta:()=>{throw new L(70);}},Za=(a,b)=>{ib[a]={ka:b}},xb=(a,b)=>{var c="/"===b,d=!b;if(c&&hb)throw new L(10);if(!c&&!d){var e=Q(b,{Ia:!1});b=e.path;e=e.node;if(e.ua)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,Za:{},Ka:b,Ra:[]};a=a.ra(b);a.ra=b;b.root=a;c?hb=a:e&&(e.ua=b,e.ra&&
e.ra.Ra.push(b))},yb=(a,b,c)=>{var d=Q(a,{parent:!0}).node;a=Ua(a);if(!a||"."===a||".."===a)throw new L(28);var e=sb(d,a);if(e)throw new L(e);if(!d.ja.xa)throw new L(63);return d.ja.xa(d,a,b,c)},S=(a,b)=>yb(a,(void 0!==b?b:511)&1023|16384,0),zb=(a,b,c)=>{"undefined"===typeof c&&(c=b,b=438);yb(a,b|8192,c)},Ab=(a,b)=>{if(!Wa(a))throw new L(44);var c=Q(b,{parent:!0}).node;if(!c)throw new L(44);b=Ua(b);var d=sb(c,b);if(d)throw new L(d);if(!c.ja.symlink)throw new L(63);c.ja.symlink(c,b,a)},ha=a=>{var b=
Q(a,{parent:!0}).node;if(!b)throw new L(44);a=Ua(a);var c=N(b,a),d=tb(b,a,!1);if(d)throw new L(d);if(!b.ja.unlink)throw new L(63);if(c.ua)throw new L(10);b.ja.unlink(b,a);ob(c)},lb=a=>{a=Q(a).node;if(!a)throw new L(44);if(!a.ja.readlink)throw new L(28);return Wa(mb(a.parent),a.ja.readlink(a))},T=(a,b)=>{a=Q(a,{sa:!b}).node;if(!a)throw new L(44);if(!a.ja.pa)throw new L(63);return a.ja.pa(a)},Bb=a=>T(a,!0),Cb=(a,b)=>{a="string"===typeof a?Q(a,{sa:!0}).node:a;if(!a.ja.oa)throw new L(63);a.ja.oa(a,{mode:b&
4095|a.mode&-4096,timestamp:Date.now()})},Db=a=>{a="string"===typeof a?Q(a,{sa:!0}).node:a;if(!a.ja.oa)throw new L(63);a.ja.oa(a,{timestamp:Date.now()})},Eb=(a,b)=>{if(0>b)throw new L(28);a="string"===typeof a?Q(a,{sa:!0}).node:a;if(!a.ja.oa)throw new L(63);if(16384===(a.mode&61440))throw new L(31);if(32768!==(a.mode&61440))throw new L(28);var c=R(a,"w");if(c)throw new L(c);a.ja.oa(a,{size:b,timestamp:Date.now()})},U=(a,b,c,d)=>{if(""===a)throw new L(44);if("string"===typeof b){var e=qb[b];if("undefined"===
typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=K(a);try{g=Q(a,{sa:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(g){if(b&128)throw new L(20);}else g=yb(a,c,0),e=!0;if(!g)throw new L(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new L(54);if(!e&&(c=g?40960===(g.mode&61440)?32:16384===(g.mode&61440)&&("r"!==rb(b)||b&512)?31:R(g,rb(b)):44))throw new L(c);b&512&&Eb(g,0);b&=-131713;
d=wb({node:g,path:mb(g),flags:b,seekable:!0,position:0,ka:g.ka,Wa:[],error:!1},d);d.ka.open&&d.ka.open(d);!f.logReadFiles||b&1||(Fb||(Fb={}),a in Fb||(Fb[a]=1));return d},Gb=a=>{if(null===a.fd)throw new L(8);a.Ca&&(a.Ca=null);try{a.ka.close&&a.ka.close(a)}catch(b){throw b;}finally{O[a.fd]=null}a.fd=null},Hb=(a,b,c)=>{if(null===a.fd)throw new L(8);if(!a.seekable||!a.ka.ta)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.ka.ta(a,b,c);a.Wa=[]},Ib=(a,b,c,d,e)=>{if(0>d||0>e)throw new L(28);
if(null===a.fd)throw new L(8);if(1===(a.flags&2097155))throw new L(8);if(16384===(a.node.mode&61440))throw new L(31);if(!a.ka.read)throw new L(28);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new L(70);b=a.ka.read(a,b,c,d,e);g||(a.position+=b);return b},Kb=(a,b,c,d,e)=>{var g=void 0;if(0>d||0>g)throw new L(28);if(null===a.fd)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(16384===(a.node.mode&61440))throw new L(31);if(!a.ka.write)throw new L(28);a.seekable&&
a.flags&1024&&Hb(a,0,2);var k="undefined"!==typeof g;if(!k)g=a.position;else if(!a.seekable)throw new L(70);b=a.ka.write(a,b,c,d,g,e);k||(a.position+=b);return b},fa=()=>{var a=a||"binary";if("utf8"!==a&&"binary"!==a)throw Error('Invalid encoding type "'+a+'"');var b;var c=U("/tmp/__dbtmp1",c||0);var d=T("/tmp/__dbtmp1").size,e=new Uint8Array(d);Ib(c,e,0,d,0);"utf8"===a?b=B(e,0):"binary"===a&&(b=e);Gb(c);return b},da=a=>{var b={};b.flags=b.flags||577;var c=U("/tmp/__dbtmp1",b.flags,b.mode);if("string"===
typeof a){var d=new Uint8Array(C(a)+1);a=y(a,d,0,d.length);Kb(c,d,0,a,b.Na)}else if(ArrayBuffer.isView(a))Kb(c,a,0,a.byteLength,b.Na);else throw Error("Unsupported data type");Gb(c)},Lb=()=>{L||(L=function(a,b){this.node=b;this.Va=function(c){this.ma=c};this.Va(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(a=>{gb[a]=new L(a);gb[a].stack="<generic error, no stack>"}))},Mb,Nb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},V=(a,b,c)=>{a=K("/dev/"+a);var d=
Nb(!!b,!!c);Ob||(Ob=64);var e=Ob++<<8|0;Za(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,k,l,n)=>{for(var p=0,t=0;t<n;t++){try{var u=b()}catch(D){throw new L(29);}if(void 0===u&&0===p)throw new L(6);if(null===u||void 0===u)break;p++;k[l+t]=u}p&&(g.node.timestamp=Date.now());return p},write:(g,k,l,n)=>{for(var p=0;p<n;p++)try{c(k[l+p])}catch(t){throw new L(29);}n&&(g.node.timestamp=Date.now());return p}});zb(a,d,e)},Ob,W={},vb,Fb,Pb={};
function Qb(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&K(b)!==K(mb(e.node)))return-54;throw e;}G[c>>2]=d.dev;G[c+4>>2]=0;G[c+8>>2]=d.ino;G[c+12>>2]=d.mode;G[c+16>>2]=d.nlink;G[c+20>>2]=d.uid;G[c+24>>2]=d.gid;G[c+28>>2]=d.rdev;G[c+32>>2]=0;Ea[c+40>>3]=BigInt(d.size);G[c+48>>2]=4096;G[c+52>>2]=d.blocks;G[c+56>>2]=d.atime.getTime()/1E3|0;G[c+60>>2]=0;G[c+64>>2]=d.mtime.getTime()/1E3|0;G[c+68>>2]=0;G[c+72>>2]=d.ctime.getTime()/1E3|0;G[c+76>>2]=0;Ea[c+80>>3]=BigInt(d.ino);return 0}var X=void 0;
function Y(){X+=4;return G[X-4>>2]}function Z(a){a=O[a];if(!a)throw new L(8);return a}function Rb(a,b,c){function d(n){return(n=n.toTimeString().match(/\(([A-Za-z ]+)\)$/))?n[1]:"GMT"}var e=(new Date).getFullYear(),g=new Date(e,0,1),k=new Date(e,6,1);e=g.getTimezoneOffset();var l=k.getTimezoneOffset();G[a>>2]=60*Math.max(e,l);G[b>>2]=Number(e!=l);a=d(g);b=d(k);a=Aa(a);b=Aa(b);l<e?(G[c>>2]=a,G[c+4>>2]=b):(G[c>>2]=b,G[c+4>>2]=a)}function Sb(a,b,c){Sb.Ma||(Sb.Ma=!0,Rb(a,b,c))}var Tb;
Tb=ma?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Ub={};function Vb(){if(!Wb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ka||"./this.program"},b;for(b in Ub)void 0===Ub[b]?delete a[b]:a[b]=Ub[b];var c=[];for(b in a)c.push(b+"="+a[b]);Wb=c}return Wb}var Wb;
function pb(a,b,c,d){a||(a=this);this.parent=a;this.ra=a.ra;this.ua=null;this.id=jb++;this.name=b;this.mode=c;this.ja={};this.ka={};this.rdev=d}Object.defineProperties(pb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Lb();P=Array(4096);xb(M,"/");S("/tmp");S("/home");S("/home/web_user");
(()=>{S("/dev");Za(259,{read:()=>0,write:(b,c,d,e)=>e});zb("/dev/null",259);Ya(1280,ab);Ya(1536,bb);zb("/dev/tty",1280);zb("/dev/tty1",1536);var a=Va();V("random",a);V("urandom",a);S("/dev/shm");S("/dev/shm/tmp")})();(()=>{S("/proc");var a=S("/proc/self");S("/proc/self/fd");xb({ra:()=>{var b=fb(a,"fd",16895,73);b.ja={lookup:(c,d)=>{var e=O[+d];if(!e)throw new L(8);c={parent:null,ra:{Ka:"fake"},ja:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Zb={a:function(a,b,c,d){x("Assertion failed: "+A(a)+", at: "+[b?A(b):"unknown filename",c,d?A(d):"unknown function"])},l:function(a,b){try{a=A(a);if(b&-8)var c=-28;else{var d=Q(a,{sa:!0}).node;d?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&R(d,a)?-2:0):c=-44}return c}catch(e){if("undefined"===typeof W||!(e instanceof L))throw e;return-e.ma}},M:function(a,b){try{return a=A(a),Cb(a,b),0}catch(c){if("undefined"===typeof W||!(c instanceof L))throw c;return-c.ma}},K:function(a){try{return a=
A(a),Db(a),0}catch(b){if("undefined"===typeof W||!(b instanceof L))throw b;return-b.ma}},j:function(a,b){try{var c=O[a];if(!c)throw new L(8);Cb(c.node,b);return 0}catch(d){if("undefined"===typeof W||!(d instanceof L))throw d;return-d.ma}},L:function(a){try{var b=O[a];if(!b)throw new L(8);Db(b.node);return 0}catch(c){if("undefined"===typeof W||!(c instanceof L))throw c;return-c.ma}},b:function(a,b,c){X=c;try{var d=Z(a);switch(b){case 0:var e=Y();return 0>e?-28:U(d.path,d.flags,0,e).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return e=Y(),d.flags|=e,0;case 5:return e=Y(),Da[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return G[Xb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"===typeof W||!(g instanceof L))throw g;return-g.ma}},H:function(a,b){try{var c=Z(a);return Qb(T,c.path,b)}catch(d){if("undefined"===typeof W||!(d instanceof L))throw d;return-d.ma}},D:function(a,b,c,d){try{b=A(b);var e=d&256;d&=4096;var g=b;if("/"===g[0])b=g;else{if(-100===a)var k="/";else{var l=
O[a];if(!l)throw new L(8);k=l.path}if(0==g.length){if(!d)throw new L(44);b=k}else b=K(k+"/"+g)}return Qb(e?Bb:T,b,c)}catch(n){if("undefined"===typeof W||!(n instanceof L))throw n;return-n.ma}},B:function(a,b){try{var c=O[a];if(!c)throw new L(8);if(0===(c.flags&2097155))throw new L(28);Eb(c.node,b);return 0}catch(d){if("undefined"===typeof W||!(d instanceof L))throw d;return-d.ma}},A:function(a,b){try{if(0===b)return-28;if(b<C("/")+1)return-68;y("/",h,a,b);return a}catch(c){if("undefined"===typeof W||
!(c instanceof L))throw c;return-c.ma}},x:function(){return 0},J:function(a,b,c){X=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Y();return G[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Y();if(!d.ka.Oa)throw new L(59);return d.ka.Oa(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:x("bad ioctl syscall "+b)}}catch(g){if("undefined"===
typeof W||!(g instanceof L))throw g;return-g.ma}},E:function(a,b){try{return a=A(a),Qb(Bb,a,b)}catch(c){if("undefined"===typeof W||!(c instanceof L))throw c;return-c.ma}},t:function(a,b){try{return a=A(a),a=K(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),S(a,b),0}catch(c){if("undefined"===typeof W||!(c instanceof L))throw c;return-c.ma}},s:function(a,b,c,d,e,g){try{a:{g<<=12;var k=!1;if(0!==(d&16)&&0!==a%65536)var l=-28;else{if(0!==(d&32)){var n=cb(b);if(!n){l=-48;break a}k=!0}else{var p=O[e];
if(!p){l=-8;break a}var t=g;if(0!==(c&2)&&0===(d&2)&&2!==(p.flags&2097155))throw new L(2);if(1===(p.flags&2097155))throw new L(2);if(!p.ka.ya)throw new L(43);var u=p.ka.ya(p,a,b,t,c,d);n=u.Ta;k=u.Aa}Pb[n]={Qa:n,Pa:b,Aa:k,fd:e,Sa:c,flags:d,offset:g};l=n}}return l}catch(D){if("undefined"===typeof W||!(D instanceof L))throw D;return-D.ma}},r:function(a,b){try{var c=Pb[a];if(0!==b&&c){if(b===c.Pa){var d=O[c.fd];if(d&&c.Sa&2){var e=c.flags,g=c.offset,k=h.slice(a,a+b);d&&d.ka.za&&d.ka.za(d,k,g,b,e)}Pb[a]=
null;c.Aa&&Yb(c.Qa)}var l=0}else l=-28;return l}catch(n){if("undefined"===typeof W||!(n instanceof L))throw n;return-n.ma}},i:function(a,b,c){X=c;try{var d=A(a),e=c?Y():0;return U(d,b,e).fd}catch(g){if("undefined"===typeof W||!(g instanceof L))throw g;return-g.ma}},q:function(a,b,c){try{a=A(a);if(0>=c)var d=-28;else{var e=lb(a),g=Math.min(c,C(e)),k=z[b+g];y(e,h,b,c+1);z[b+g]=k;d=g}return d}catch(l){if("undefined"===typeof W||!(l instanceof L))throw l;return-l.ma}},p:function(a){try{a=A(a);var b=Q(a,
{parent:!0}).node,c=Ua(a),d=N(b,c),e=tb(b,c,!0);if(e)throw new L(e);if(!b.ja.rmdir)throw new L(63);if(d.ua)throw new L(10);b.ja.rmdir(b,c);ob(d);return 0}catch(g){if("undefined"===typeof W||!(g instanceof L))throw g;return-g.ma}},F:function(a,b){try{return a=A(a),Qb(T,a,b)}catch(c){if("undefined"===typeof W||!(c instanceof L))throw c;return-c.ma}},o:function(a){try{return a=A(a),ha(a),0}catch(b){if("undefined"===typeof W||!(b instanceof L))throw b;return-b.ma}},e:function(){x("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
k:function(){x("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},v:function(a,b){a=new Date(1E3*G[a>>2]);G[b>>2]=a.getSeconds();G[b+4>>2]=a.getMinutes();G[b+8>>2]=a.getHours();G[b+12>>2]=a.getDate();G[b+16>>2]=a.getMonth();G[b+20>>2]=a.getFullYear()-1900;G[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);G[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;G[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();c=c.getTimezoneOffset();G[b+32>>2]=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0},w:Sb,m:function(){x("")},f:Tb,I:function(a,b,c){h.copyWithin(a,b,b+c)},d:function(a){var b=h.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ta.grow(Math.min(2147483648,d)-Ca.byteLength+65535>>>16);Fa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},y:function(a,b){var c=
0;Vb().forEach(function(d,e){var g=b+c;e=G[a+4*e>>2]=g;for(g=0;g<d.length;++g)z[e++>>0]=d.charCodeAt(g);z[e>>0]=0;c+=d.length+1});return 0},z:function(a,b){var c=Vb();G[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});G[b>>2]=d;return 0},c:function(a){try{var b=Z(a);Gb(b);return 0}catch(c){if("undefined"===typeof W||!(c instanceof L))throw c;return c.ma}},n:function(a,b){try{var c=Z(a);z[b>>0]=c.tty?2:16384===(c.mode&61440)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){if("undefined"===
typeof W||!(d instanceof L))throw d;return d.ma}},h:function(a,b,c,d){try{a:{for(var e=Z(a),g=a=0;g<c;g++){var k=G[b+(8*g+4)>>2],l=Ib(e,z,G[b+8*g>>2],k,void 0);if(0>l){var n=-1;break a}a+=l;if(l<k)break}n=a}G[d>>2]=n;return 0}catch(p){if("undefined"===typeof W||!(p instanceof L))throw p;return p.ma}},u:function(a,b,c,d){try{var e=Number(b&BigInt(4294967295))|0,g=Number(b>>BigInt(32))|0,k=Z(a);a=4294967296*g+(e>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Hb(k,a,c);Ea[d>>3]=BigInt(k.position);
k.Ca&&0===a&&0===c&&(k.Ca=null);return 0}catch(l){if("undefined"===typeof W||!(l instanceof L))throw l;return l.ma}},C:function(a){try{var b=Z(a);return b.ka&&b.ka.fsync?-b.ka.fsync(b):0}catch(c){if("undefined"===typeof W||!(c instanceof L))throw c;return c.ma}},g:function(a,b,c,d){try{a:{for(var e=Z(a),g=a=0;g<c;g++){var k=Kb(e,z,G[b+8*g>>2],G[b+(8*g+4)>>2]);if(0>k){var l=-1;break a}a+=k}l=a}G[d>>2]=l;return 0}catch(n){if("undefined"===typeof W||!(n instanceof L))throw n;return n.ma}},G:function(a){var b=
Date.now();G[a>>2]=b/1E3|0;G[a+4>>2]=b%1E3*1E3|0;return 0},N:function(a){var b=Date.now()/1E3|0;a&&(G[a>>2]=b);return b},O:function(a,b){if(b){var c=b+8;b=1E3*G[c>>2];b+=G[c+4>>2]/1E3}else b=Date.now();a=A(a);try{var d=Q(a,{sa:!0}).node;d.ja.oa(d,{timestamp:Math.max(b,b)});var e=0}catch(g){if(!(g instanceof L)){b:{e=Error();if(!e.stack){try{throw Error();}catch(k){e=k}if(!e.stack){e="(no stack trace available)";break b}}e=e.stack.toString()}f.extraStackTrace&&(e+="\n"+f.extraStackTrace());e=Ra(e);
throw g+" : "+e;}e=g.ma;G[Xb()>>2]=e;e=-1}return e}};
(function(){function a(e){f.asm=e.exports;ta=f.asm.P;Fa();Ga=f.asm.ea;Ia.unshift(f.asm.Q);H--;f.monitorRunDependencies&&f.monitorRunDependencies(H);0==H&&(null!==La&&(clearInterval(La),La=null),I&&(e=I,I=null,e()))}function b(e){a(e.instance)}function c(e){return Pa().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){v("failed to asynchronously prepare wasm: "+g);x(g)})}var d={a:Zb};H++;f.monitorRunDependencies&&f.monitorRunDependencies(H);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return v("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return w||"function"!==typeof WebAssembly.instantiateStreaming||Ma()||J.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){v("wasm streaming compile failed: "+g);v("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Q).apply(null,arguments)};var ca=f._sqlite3_malloc=function(){return(ca=f._sqlite3_malloc=f.asm.R).apply(null,arguments)},ea=f._sqlite3_free=function(){return(ea=f._sqlite3_free=f.asm.S).apply(null,arguments)};f._sqlite3_errmsg=function(){return(f._sqlite3_errmsg=f.asm.T).apply(null,arguments)};
var ia=f._sqlite3_initialize=function(){return(ia=f._sqlite3_initialize=f.asm.U).apply(null,arguments)},Xb=f.___errno_location=function(){return(Xb=f.___errno_location=f.asm.V).apply(null,arguments)},Ba=f._malloc=function(){return(Ba=f._malloc=f.asm.W).apply(null,arguments)},Yb=f._free=function(){return(Yb=f._free=f.asm.X).apply(null,arguments)};f.___dbFileImportOrExport=function(){return(f.___dbFileImportOrExport=f.asm.Y).apply(null,arguments)};
f._dbClose=function(){return(f._dbClose=f.asm.Z).apply(null,arguments)};f._dbExec=function(){return(f._dbExec=f.asm._).apply(null,arguments)};f._jsbatonValueStringArgi=function(){return(f._jsbatonValueStringArgi=f.asm.$).apply(null,arguments)};f._dbFileImportOrExport=function(){return(f._dbFileImportOrExport=f.asm.aa).apply(null,arguments)};f._dbNoop=function(){return(f._dbNoop=f.asm.ba).apply(null,arguments)};f._dbOpen=function(){return(f._dbOpen=f.asm.ca).apply(null,arguments)};
f._jsbatonValueErrmsg=function(){return(f._jsbatonValueErrmsg=f.asm.da).apply(null,arguments)};var db=f._memalign=function(){return(db=f._memalign=f.asm.fa).apply(null,arguments)},xa=f.stackSave=function(){return(xa=f.stackSave=f.asm.ga).apply(null,arguments)},ya=f.stackRestore=function(){return(ya=f.stackRestore=f.asm.ha).apply(null,arguments)},wa=f.stackAlloc=function(){return(wa=f.stackAlloc=f.asm.ia).apply(null,arguments)};f.cwrap=m;var $b;I=function ac(){$b||bc();$b||(I=ac)};
function bc(){function a(){if(!$b&&($b=!0,f.calledRun=!0,!ua)){f.noFSInit||Mb||(Mb=!0,Lb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?V("stdin",f.stdin):Ab("/dev/tty","/dev/stdin"),f.stdout?V("stdout",null,f.stdout):Ab("/dev/tty","/dev/stdout"),f.stderr?V("stderr",null,f.stderr):Ab("/dev/tty1","/dev/stderr"),U("/dev/stdin",0),U("/dev/stdout",1),U("/dev/stderr",1));kb=!1;Qa(Ia);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=
[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ja.unshift(b)}Qa(Ja)}}if(!(0<H)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ka();Qa(Ha);0<H||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=bc;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();bc();

}());
/*jslint-enable*/
