# Publishing packages to npm and GitHub Packages
# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-npm-and-github-packages
name: publish
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:


# npm publish - start
  job1:
    strategy:
      matrix:
        architecture:
          # - arm64
          - x64
          # - x86
        node_version:
          # - 14
          - 16
          # - 18
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
    name: >
      job1
      node
      v${{ matrix.node_version }}
      ${{ matrix.architecture }}
      ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:

      # Setup .npmrc file to publish to GitHub Packages
      - run: rm -f /home/runner/work/_temp/.npmrc
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@octocat'
      # Publish to GitHub Packages
      - run: sh jslint_ci.sh shCiNpmPublish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_REGISTRY: github

      # Setup .npmrc file to publish to npm
      - run: rm -f /home/runner/work/_temp/.npmrc
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          registry-url: 'https://registry.npmjs.org'
      # Publish to npm
      - run: sh jslint_ci.sh shCiNpmPublish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_REGISTRY: npm
# npm publish - end
