
/*jslint-disable*/
(function () {
    "use strict";

var e;e||(e=typeof Module !== 'undefined' ? Module : {});var ba=Object.assign;null;let k={},n,ca,da;
function ea(a){function b(r){null!=n&&n.close();return n=new da.Database(r)}let c=a.argList,d=new Uint8Array(a.baton&&a.baton.buffer);let f,g=a.cFuncName;var m=a.id;switch(g){case "_dbClose":case "_dbExec":case "_dbMemoryLoadOrSave":case "_dbNoop":case "_dbOpen":case "_dbTableInsert":try{f=v(d.byteLength);w.set(d,f);k[g](f);var q=fa(f+272);d.set(new Uint8Array(w.buffer,w.byteOffset+f,1024));d=new BigInt64Array(d.buffer,8);d.subarray(16,32).forEach(function(r,t){r=Number(r);0===r?c[t]=d[t]:(c[t]=new ArrayBuffer(Number(d[t])),
(new Uint8Array(c[t])).set(w.subarray(r,r+c[t].byteLength)))});ha(f)}catch(r){q=q||r.message}postMessage({argList:c,baton:new DataView(d.buffer),cFuncName:g,errmsg:q,id:m},[d.buffer,...c.filter(function(r){return r&&r.constructor===ArrayBuffer})]);return}q=a.sql;switch(a.action){case "open":return a=a.buffer,b(a&&new Uint8Array(a)),postMessage({id:m,ready:!0});case "exec":null===n&&b();if(!q)throw"exec: Missing query string";return postMessage({id:m,results:n.exec(q,a.params)});case "export":a=n["export"]();
m={id:m,buffer:a};try{return postMessage(m,[m])}catch(r){return postMessage(m)}case "close":return n&&n.close(),postMessage({id:m});default:throw Error("Invalid action : "+a.action);}}self.onmessage=async function({data:a}){da=da||await ca;try{await ea(a)}catch(b){postMessage({id:a.id,errmsg:b.message})}};ca=new Promise(function(a){e.postRun=a});
e.onRuntimeInitialized=function(){function a(h,l){this.$a=h;this.db=l;this.Za=1;this.ub=[]}function b(h,l){this.db=l;l=ia(h)+1;this.nb=v(l);if(null===this.nb)throw Error("Unable to allocate memory for the SQL string");x(h,w,this.nb,l);this.sb=this.nb;this.jb=this.yb=null}function c(h){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=h){var l=this.filename,p="/",u=l;p&&(p="string"===typeof p?p:ja(p),u=l?A(p+"/"+l):p);l=ka(!0,!0);u=la(u,(void 0!==l?l:438)&4095|32768,0);if(h){if("string"===
typeof h){p=Array(h.length);for(var z=0,P=h.length;z<P;++z)p[z]=h.charCodeAt(z);h=p}ma(u,l|146);p=B(u,577);na(p,h,0,h.length,0,void 0);oa(p);ma(u,l)}}this.handleError(g(this.filename,d));this.db=E(d,"i32");this.ob={};this.gb={}}let d=F(4),f=e.cwrap;k._dbClose=qa;k._dbExec=ra;k._dbMemoryLoadOrSave=sa;k._dbNoop=ta;k._dbOpen=ua;k._dbTableInsert=va;let g=f("sqlite3_open","number",["string","number"]),m=f("sqlite3_close_v2","number",["number"]),q=f("sqlite3_exec","number",["number","string","number","number",
"number"]),r=f("sqlite3_changes","number",["number"]),t=f("sqlite3_prepare_v2","number",["number","string","number","number","number"]),y=f("sqlite3_sql","string",["number"]),H=f("sqlite3_normalized_sql","string",["number"]),aa=f("sqlite3_prepare_v2","number",["number","number","number","number","number"]),tc=f("sqlite3_bind_text","number",["number","number","number","number","number"]),zb=f("sqlite3_bind_blob","number",["number","number","number","number","number"]),uc=f("sqlite3_bind_double","number",
["number","number","number"]),vc=f("sqlite3_bind_int","number",["number","number","number"]),wc=f("sqlite3_bind_parameter_index","number",["number","string"]),xc=f("sqlite3_step","number",["number"]),yc=f("sqlite3_errmsg","string",["number"]),zc=f("sqlite3_column_count","number",["number"]),Ac=f("sqlite3_data_count","number",["number"]),Bc=f("sqlite3_column_double","number",["number","number"]),Ab=f("sqlite3_column_text","string",["number","number"]),Cc=f("sqlite3_column_blob","number",["number",
"number"]),Dc=f("sqlite3_column_bytes","number",["number","number"]),Ec=f("sqlite3_column_type","number",["number","number"]),Fc=f("sqlite3_column_name","string",["number","number"]),Gc=f("sqlite3_reset","number",["number"]),Hc=f("sqlite3_clear_bindings","number",["number"]),Ic=f("sqlite3_finalize","number",["number"]),Jc=f("sqlite3_create_function_v2","number","number string number number number number number number number".split(" ")),Kc=f("sqlite3_value_type","number",["number"]),Lc=f("sqlite3_value_bytes",
"number",["number"]),Mc=f("sqlite3_value_text","string",["number"]),Nc=f("sqlite3_value_blob","number",["number"]),Oc=f("sqlite3_value_double","number",["number"]),Pc=f("sqlite3_result_double","",["number","number"]),Bb=f("sqlite3_result_null","",["number"]),Qc=f("sqlite3_result_text","",["number","string","number","number"]),Rc=f("sqlite3_result_blob","",["number","number","number","number"]),Sc=f("sqlite3_result_int","",["number","number"]),Cb=f("sqlite3_result_error","",["number","string","number"]);
a.prototype.bind=function(h){if(!this.$a)throw"Statement closed";this.reset();return Array.isArray(h)?this.Mb(h):null!=h&&"object"===typeof h?this.Nb(h):!0};a.prototype.step=function(){if(!this.$a)throw"Statement closed";this.Za=1;let h=xc(this.$a);switch(h){case 100:return!0;case 101:return!1;default:throw this.db.handleError(h);}};a.prototype.Ib=function(h){null==h&&(h=this.Za,this.Za+=1);return Bc(this.$a,h)};a.prototype.Rb=function(h){null==h&&(h=this.Za,this.Za+=1);h=Ab(this.$a,h);if("function"!==
typeof BigInt)throw Error("BigInt is not supported");return BigInt(h)};a.prototype.Sb=function(h){null==h&&(h=this.Za,this.Za+=1);return Ab(this.$a,h)};a.prototype.getBlob=function(h){null==h&&(h=this.Za,this.Za+=1);let l=Dc(this.$a,h);h=Cc(this.$a,h);let p=new Uint8Array(l);for(let u=0;u<l;u+=1)p[u]=G(h+u,1,0);return p};a.prototype.get=function(h,l){l=l||{};null!=h&&this.bind(h)&&this.step();h=[];let p=Ac(this.$a);for(let u=0;u<p;u+=1)switch(Ec(this.$a,u)){case 1:let z=l.useBigInt?this.Rb(u):this.Ib(u);
h.push(z);break;case 2:h.push(this.Ib(u));break;case 3:h.push(this.Sb(u));break;case 4:h.push(this.getBlob(u));break;default:h.push(null)}return h};a.prototype.getColumnNames=function(){let h=[],l=zc(this.$a);for(let p=0;p<l;p+=1)h.push(Fc(this.$a,p));return h};a.prototype.getAsObject=function(h,l){h=this.get(h,l);l=this.getColumnNames();let p={};for(let u=0;u<l.length;u+=1)p[l[u]]=h[u];return p};a.prototype.getSQL=function(){return y(this.$a)};a.prototype.getNormalizedSQL=function(){return H(this.$a)};
a.prototype.run=function(h){null!=h&&this.bind(h);this.step();return this.reset()};a.prototype.Db=function(h,l){null==l&&(l=this.Za,this.Za+=1);h=wa(h);let p=v(h.length);this.ub.push(p);this.db.handleError(tc(this.$a,l,p,h.length-1,0))};a.prototype.Lb=function(h,l){null==l&&(l=this.Za,this.Za+=1);let p=v(h.length);this.ub.push(p);this.db.handleError(zb(this.$a,l,p,h.length,0))};a.prototype.Cb=function(h,l){null==l&&(l=this.Za,this.Za+=1);this.db.handleError((h===(h|0)?vc:uc)(this.$a,l,h))};a.prototype.Ob=
function(h){null==h&&(h=this.Za,this.Za+=1);zb(this.$a,h,0,0,0)};a.prototype.Eb=function(h,l){null==l&&(l=this.Za,this.Za+=1);switch(typeof h){case "string":this.Db(h,l);return;case "number":this.Cb(h,l);return;case "bigint":this.Db(h.toString(),l);return;case "boolean":this.Cb(h+0,l);return;case "object":if(null===h){this.Ob(l);return}if(null!=h.length){this.Lb(h,l);return}}throw"Wrong API use : tried to bind a value of an unknown type ("+h+").";};a.prototype.Nb=function(h){let l=this;Object.keys(h).forEach(function(p){let u=
wc(l.$a,p);0!==u&&l.Eb(h[p],u)});return!0};a.prototype.Mb=function(h){for(let l=0;l<h.length;l+=1)this.Eb(h[l],l+1);return!0};a.prototype.reset=function(){this.freemem();return 0===Hc(this.$a)&&0===Gc(this.$a)};a.prototype.freemem=function(){let h;for(;void 0!==(h=this.ub.pop());)ha(h)};a.prototype.free=function(){let h;this.freemem();h=0===Ic(this.$a);delete this.db.ob[this.$a];this.$a=0;return h};b.prototype.next=function(){if(null===this.nb)return{done:!0};null!==this.jb&&(this.jb.free(),this.jb=
null);if(!this.db.db)throw this.wb(),Error("Database closed");let h=xa(),l=F(4);za(d,0,"i32");za(l,0,"i32");try{this.db.handleError(aa(this.db.db,this.sb,-1,d,l));this.sb=E(l,"i32");let p=E(d,"i32");if(0===p)return this.wb(),{done:!0};this.jb=new a(p,this.db);this.db.ob[p]=this.jb;return{value:this.jb,done:!1}}catch(p){throw this.yb=I(this.sb),this.wb(),p;}finally{Aa(h)}};b.prototype.wb=function(){ha(this.nb);this.nb=null};b.prototype.getRemainingSQL=function(){return null!==this.yb?this.yb:I(this.sb)};
"function"===typeof Symbol&&"symbol"===typeof Symbol.iterator&&(b.prototype[Symbol.iterator]=function(){return this});c.prototype.run=function(h,l){if(!this.db)throw"Database closed";if(l){h=this.prepare(h,l);try{h.step()}finally{h.free()}}else this.handleError(q(this.db,h,0,0,d));return this};c.prototype.exec=function(h,l,p){if(!this.db)throw"Database closed";let u=xa(),z=null;try{var P=ia(h)+1,C=F(P);x(h,J,C,P);h=C;let U=F(4);for(P=[];0!==E(h,"i8");){za(d,0,"i32");za(U,0,"i32");this.handleError(aa(this.db,
h,-1,d,U));let D=E(d,"i32");h=E(U,"i32");if(0!==D){C=null;z=new a(D,this);for(null!=l&&z.bind(l);z.step();)null===C&&(C={columns:z.getColumnNames(),values:[]},P.push(C)),C.values.push(z.get(null,p));z.free()}}return P}catch(U){throw z&&z.free(),U;}finally{Aa(u)}};c.prototype.each=function(h,l,p,u,z){"function"===typeof l&&(u=p,p=l,l=void 0);h=this.prepare(h,l);try{for(;h.step();)p(h.getAsObject(null,z))}finally{h.free()}if("function"===typeof u)return u()};c.prototype.prepare=function(h,l){za(d,0,
"i32");this.handleError(t(this.db,h,-1,d,0));h=E(d,"i32");if(0===h)throw"Nothing to prepare";let p=new a(h,this);null!=l&&p.bind(l);return this.ob[h]=p};c.prototype.iterateStatements=function(h){return new b(h,this)};c.prototype["export"]=function(){Object.values(this.ob).forEach(function(l){l.free()});Object.values(this.gb).forEach(Ba);this.gb={};this.handleError(m(this.db));let h=Ca(this.filename);this.handleError(g(this.filename,d));this.db=E(d,"i32");return h};c.prototype.close=function(){null!==
this.db&&(Object.values(this.ob).forEach(function(h){h.free()}),Object.values(this.gb).forEach(Ba),this.gb={},this.handleError(m(this.db)),Da("/"+this.filename),this.db=null)};c.prototype.handleError=function(h){if(0===h)return null;h=yc(this.db);throw Error(h);};c.prototype.getRowsModified=function(){return r(this.db)};c.prototype.create_function=function(h,l){Object.prototype.hasOwnProperty.call(this.gb,h)&&(Ba(this.gb[h]),delete this.gb[h]);let p=Ea(function(u,z,P){let C,U=[];for(let pa=0;pa<z;pa+=
1){var D=E(P+4*pa,"i32"),Q=Kc(D);if(1===Q||2===Q)D=Oc(D);else if(3===Q)D=Mc(D);else if(4===Q){Q=D;D=Lc(Q);Q=Nc(Q);let Fb=new Uint8Array(D);for(let ya=0;ya<D;ya+=1)Fb[ya]=G(Q+ya,1,0);D=Fb}else D=null;U.push(D)}try{C=l.apply(null,U)}catch(pa){Cb(u,pa,-1);return}switch(typeof C){case "boolean":Sc(u,C?1:0);break;case "number":Pc(u,C);break;case "string":Qc(u,C,-1,-1);break;case "object":null===C?Bb(u):null!=C.length?(z=v(C.length),Rc(u,z,C.length,-1),ha(z)):Cb(u,"Wrong API use : tried to return a value of an unknown type ("+
C+").",-1);break;default:Bb(u)}});this.gb[h]=p;this.handleError(Jc(this.db,h,l.length,1,0,p,0,0,0));return this};e.Database=c};var Fa=ba({},e),Ga="./this.program",Ha="object"===typeof window,Ia="function"===typeof importScripts,Ja="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,K="",Ka,La,Ma,fs,Na,Oa;
if(Ja)K=Ia?require("path").dirname(K)+"/":__dirname+"/",Oa=()=>{Na||(fs=require("fs"),Na=require("path"))},Ka=function(a,b){Oa();a=Na.normalize(a);return fs.readFileSync(a,b?null:"utf8")},Ma=a=>{a=Ka(a,!0);a.buffer||(a=new Uint8Array(a));return a},La=(a,b,c)=>{Oa();a=Na.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(Ga=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),e.inspect=function(){return"[Emscripten Module object]"};
else if(Ha||Ia)Ia?K=self.location.href:"undefined"!==typeof document&&document.currentScript&&(K=document.currentScript.src),K=0!==K.indexOf("blob:")?K.substr(0,K.replace(/[?#].*/,"").lastIndexOf("/")+1):"",Ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},Ia&&(Ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),La=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var Pa=e.print||console.log.bind(console),Qa=e.printErr||console.warn.bind(console);ba(e,Fa);Fa=null;e.thisProgram&&(Ga=e.thisProgram);var Ra=[],Sa;
function Ea(a){if(!Sa){Sa=new WeakMap;for(var b=L.length,c=0;c<0+b;c++){var d=L.get(c);d&&Sa.set(d,c)}}if(Sa.has(a))return Sa.get(a);if(Ra.length)b=Ra.pop();else{try{L.grow(1)}catch(g){if(!(g instanceof RangeError))throw g;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}b=L.length-1}try{L.set(b,a)}catch(g){if(!(g instanceof TypeError))throw g;if("function"===typeof WebAssembly.Function){d={i:"i32",j:"i64",f:"f32",d:"f64"};var f={parameters:[],results:[]};for(c=1;4>c;++c)f.parameters.push(d["viii"[c]]);
c=new WebAssembly.Function(f,a)}else{d=[1,0,1,96];f={i:127,j:126,f:125,d:124};d.push(3);for(c=0;3>c;++c)d.push(f["iii"[c]]);d.push(0);d[1]=d.length-2;c=new Uint8Array([0,97,115,109,1,0,0,0].concat(d,[2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0]));c=new WebAssembly.Module(c);c=(new WebAssembly.Instance(c,{e:{f:a}})).exports.f}L.set(b,c)}Sa.set(a,b);return b}function Ba(a){Sa.delete(L.get(a));Ra.push(a)}var Ta;e.wasmBinary&&(Ta=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;
"object"!==typeof WebAssembly&&M("no native wasm support detected");
function za(a,b,c="i8",d){"*"===c.charAt(c.length-1)&&(c="i32");if(d)switch(c){case "i1":J[a>>0]=b;break;case "i8":J[a>>0]=b;break;case "i16":Ua[a>>1]=b;break;case "i32":Va[a>>2]=b;break;case "i64":Wa[a>>3]=BigInt(b);break;case "float":Xa[a>>2]=b;break;case "double":Ya[a>>3]=b;break;default:M("invalid type for setValue: "+c)}else switch(c){case "i1":N(a|0,b|0,1);break;case "i8":N(a|0,b|0,1);break;case "i16":N(a|0,b|0,2);break;case "i32":N(a|0,b|0,4);break;case "i64":N(a|0,b|0,8);break;case "float":b=
Math.fround(b);N(a|0,b,4,!0);break;case "double":N(a|0,+b,8,!0);break;default:M("invalid type for setValue: "+c)}}
function E(a,b="i8",c){"*"===b.charAt(b.length-1)&&(b="i32");if(c)switch(b){case "i1":return J[a>>0];case "i8":return J[a>>0];case "i16":return Ua[a>>1];case "i32":return Va[a>>2];case "i64":return Number(Wa[a>>3]);case "float":return Xa[a>>2];case "double":return Number(Ya[a>>3]);default:M("invalid type for getValue: "+b)}else switch(b){case "i1":return G(a|0,1,0)|0;case "i8":return G(a|0,1,0)|0;case "i16":return G(a|0,2,0)|0;case "i32":return G(a|0,4,0)|0;case "i64":return G(a|0,8,0)|0;case "float":return Math.fround(G(a|
0,4,0,!0));case "double":return+G(a|0,8,0,!0);default:M("invalid type for getValue: "+b)}return null}function Za(a,b){switch(a){case 1:return"i8";case 2:return"i16";case 4:return b?"float":"i32";case 8:return b?"double":"i64";default:M(void 0)}}
function N(a,b,c,d){0>=a&&M("segmentation fault storing "+c+" bytes to address "+a);0!==a%c&&M("alignment error storing to address "+a+", which was expected to be aligned to a multiple of "+c);if($a&&!ab){var f=bb()>>>0;a+c>f&&M("segmentation fault, exceeded the top of the available dynamic heap when storing "+c+" bytes to address "+a+". DYNAMICTOP="+f);f>=cb()||M(void 0);f<=J.length||M(void 0)}za(a,b,Za(c,d),1)}
function G(a,b,c,d){0>=a&&M("segmentation fault loading "+b+" bytes from address "+a);0!==a%b&&M("alignment error loading from address "+a+", which was expected to be aligned to a multiple of "+b);if($a&&!ab){var f=bb()>>>0;a+b>f&&M("segmentation fault, exceeded the top of the available dynamic heap when loading "+b+" bytes from address "+a+". DYNAMICTOP="+f);f>=cb()||M(void 0);f<=J.length||M(void 0)}b=Za(b,d);a=E(a,b,1);c&&(c=parseInt(b.substr(1),10),a=0<=a?a:32>=c?2*Math.abs(1<<c-1)+a:Math.pow(2,
c)+a);return a}var db,eb=!1;function fb(a,b,c,d){var f={string:function(t){var y=0;if(null!==t&&void 0!==t&&0!==t){var H=(t.length<<2)+1;y=F(H);x(t,w,y,H)}return y},array:function(t){var y=F(t.length);J.set(t,y);return y}};a=e["_"+a];var g=[],m=0;if(d)for(var q=0;q<d.length;q++){var r=f[c[q]];r?(0===m&&(m=xa()),g[q]=r(d[q])):g[q]=d[q]}c=a.apply(null,g);return c=function(t){0!==m&&Aa(m);return"string"===b?I(t):"boolean"===b?!!t:t}(c)}
var gb="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function hb(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&gb)return gb.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var m=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|m:(f&7)<<18|g<<12|m<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function I(a,b){return a?hb(w,a,b):""}
function x(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var m=a.charCodeAt(g);if(55296<=m&&57343>=m){var q=a.charCodeAt(++g);m=65536+((m&1023)<<10)|q&1023}if(127>=m){if(c>=d)break;b[c++]=m}else{if(2047>=m){if(c+1>=d)break;b[c++]=192|m>>6}else{if(65535>=m){if(c+2>=d)break;b[c++]=224|m>>12}else{if(c+3>=d)break;b[c++]=240|m>>18;b[c++]=128|m>>12&63}b[c++]=128|m>>6&63}b[c++]=128|m&63}}b[c]=0;return c-f}
function ia(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function fa(a){for(var b="";;){var c=G(a++|0,1,1)>>>0;if(!c)return b;b+=String.fromCharCode(c)}}function ib(a){var b=ia(a)+1,c=v(b);c&&x(a,J,c,b);return c}var jb,J,w,Ua,Va,Xa,Ya,Wa;
function kb(){var a=db.buffer;jb=a;e.HEAP8=J=new Int8Array(a);e.HEAP16=Ua=new Int16Array(a);e.HEAP32=Va=new Int32Array(a);e.HEAPU8=w=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=Xa=new Float32Array(a);e.HEAPF64=Ya=new Float64Array(a);e.HEAP64=Wa=new BigInt64Array(a);e.HEAPU64=new BigUint64Array(a)}var L,lb=[],mb=[],nb=[],$a=!1,ab=!1;function ob(){var a=e.preRun.shift();lb.unshift(a)}var pb=0,qb=null,rb=null;e.preloadedImages={};e.preloadedAudios={};
function M(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";Qa(a);eb=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function sb(){return O.startsWith("data:application/octet-stream;base64,")}var O;O="sqlmath_wasm.wasm";if(!sb()){var tb=O;O=e.locateFile?e.locateFile(tb,K):K+tb}function ub(){var a=O;try{if(a==O&&Ta)return new Uint8Array(Ta);if(Ma)return Ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){M(b)}}
function vb(){if(!Ta&&(Ha||Ia)){if("function"===typeof fetch&&!O.startsWith("file://"))return fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return ub()});if(La)return new Promise(function(a,b){La(O,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return ub()})}
function wb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.bc;"number"===typeof c?void 0===b.vb?L.get(c)():L.get(c)(b.vb):c(void 0===b.vb?null:b.vb)}}}function xb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}function yb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function A(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=yb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Db(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Eb(a){if("/"===a)return"/";a=A(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Gb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(Ja)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){M("randomDevice")}}
function Hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=yb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ib=[];function Jb(a,b){Ib[a]={input:[],output:[],mb:b};Kb(a,Lb)}
var Lb={open:function(a){var b=Ib[a.node.rdev];if(!b)throw new R(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.mb.flush(a.tty)},flush:function(a){a.tty.mb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.mb.Jb)throw new R(60);for(var f=0,g=0;g<d;g++){try{var m=a.tty.mb.Jb(a.tty)}catch(q){throw new R(29);}if(void 0===m&&0===f)throw new R(6);if(null===m||void 0===m)break;f++;b[c+g]=m}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.mb.zb)throw new R(60);
try{for(var f=0;f<d;f++)a.tty.mb.zb(a.tty,b[c+f])}catch(g){throw new R(29);}d&&(a.node.timestamp=Date.now());return f}},Mb={Jb:function(a){if(!a.input.length){var b=null;if(Ja){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=wa(b,!0)}return a.input.shift()},zb:function(a,b){null===b||10===b?(Pa(hb(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(Pa(hb(a.output,0)),a.output=[])}},Nb={zb:function(a,b){null===b||10===b?(Qa(hb(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(Qa(hb(a.output,0)),a.output=[])}};
function Ob(a){a=65536*Math.ceil(a/65536);var b=Pb(65536,a);if(!b)return 0;w.fill(0,b,b+a);return b}
var S={eb:null,fb:function(){return S.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R(63);S.eb||(S.eb={dir:{node:{cb:S.Va.cb,bb:S.Va.bb,lookup:S.Va.lookup,pb:S.Va.pb,rename:S.Va.rename,unlink:S.Va.unlink,rmdir:S.Va.rmdir,readdir:S.Va.readdir,symlink:S.Va.symlink},stream:{ib:S.Wa.ib}},file:{node:{cb:S.Va.cb,bb:S.Va.bb},stream:{ib:S.Wa.ib,read:S.Wa.read,write:S.Wa.write,Bb:S.Wa.Bb,qb:S.Wa.qb,rb:S.Wa.rb}},link:{node:{cb:S.Va.cb,bb:S.Va.bb,
readlink:S.Va.readlink},stream:{}},Fb:{node:{cb:S.Va.cb,bb:S.Va.bb},stream:Qb}});c=Rb(a,b,c,d);16384===(c.mode&61440)?(c.Va=S.eb.dir.node,c.Wa=S.eb.dir.stream,c.Xa={}):32768===(c.mode&61440)?(c.Va=S.eb.file.node,c.Wa=S.eb.file.stream,c.ab=0,c.Xa=null):40960===(c.mode&61440)?(c.Va=S.eb.link.node,c.Wa=S.eb.link.stream):8192===(c.mode&61440)&&(c.Va=S.eb.Fb.node,c.Wa=S.eb.Fb.stream);c.timestamp=Date.now();a&&(a.Xa[b]=c,a.timestamp=c.timestamp);return c},cc:function(a){return a.Xa?a.Xa.subarray?a.Xa.subarray(0,
a.ab):new Uint8Array(a.Xa):new Uint8Array(0)},Gb:function(a,b){var c=a.Xa?a.Xa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Xa,a.Xa=new Uint8Array(b),0<a.ab&&a.Xa.set(c.subarray(0,a.ab),0))},Zb:function(a,b){if(a.ab!=b)if(0==b)a.Xa=null,a.ab=0;else{var c=a.Xa;a.Xa=new Uint8Array(b);c&&a.Xa.set(c.subarray(0,Math.min(b,a.ab)));a.ab=b}},Va:{cb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;
16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ab:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Pb=4096;b.blocks=Math.ceil(b.size/b.Pb);return b},bb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&S.Zb(a,b.size)},lookup:function(){throw Sb[44];},pb:function(a,b,c,d){return S.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===
(a.mode&61440)){try{var d=Tb(b,c)}catch(g){}if(d)for(var f in d.Xa)throw new R(55);}delete a.parent.Xa[a.name];a.parent.timestamp=Date.now();a.name=c;b.Xa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Xa[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Tb(a,b),d;for(d in c.Xa)throw new R(55);delete a.Xa[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Xa)a.Xa.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=S.createNode(a,
b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},Wa:{read:function(a,b,c,d,f){var g=a.node.Xa;if(f>=a.node.ab)return 0;a=Math.min(a.node.ab-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===J.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Xa||a.Xa.subarray)){if(g)return a.Xa=b.subarray(c,c+d),a.ab=d;if(0===a.ab&&0===f)return a.Xa=
b.slice(c,c+d),a.ab=d;if(f+d<=a.ab)return a.Xa.set(b.subarray(c,c+d),f),d}S.Gb(a,f+d);if(a.Xa.subarray&&b.subarray)a.Xa.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Xa[f+g]=b[c+g];a.ab=Math.max(a.ab,f+d);return d},ib:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ab);if(0>b)throw new R(28);return b},Bb:function(a,b,c){S.Gb(a.node,b+c);a.node.ab=Math.max(a.node.ab,b+c)},qb:function(a,b,c,d,f,g){if(0!==b)throw new R(28);if(32768!==(a.node.mode&61440))throw new R(43);
a=a.node.Xa;if(g&2||a.buffer!==jb){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=Ob(c);if(!c)throw new R(48);J.set(a,c)}else d=!1,c=a.byteOffset;return{Yb:c,tb:d}},rb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new R(43);if(f&2)return 0;S.Wa.write(a,b,0,d,c,!1);return 0}}},Ub=null,Vb={},T=[],Wb=1,V=null,Xb=!0,R=null,Sb={},W=(a,b={})=>{a=Hb("/",a);if(!a)return{path:"",node:null};var c={Hb:!0,Ab:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);
if(8<b.Ab)throw new R(32);a=yb(a.split("/").filter(m=>!!m),!1);var f=Ub;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Tb(f,a[d]);c=A(c+"/"+a[d]);f.kb&&(!g||g&&b.Hb)&&(f=f.kb.root);if(!g||b.hb)for(g=0;40960===(f.mode&61440);)if(f=Yb(c),c=Hb(Db(c),f),f=W(c,{Ab:b.Ab}).node,40<g++)throw new R(32);}return{path:c,node:f}},ja=a=>{for(var b;;){if(a===a.parent)return a=a.fb.Kb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Zb=(a,b)=>{for(var c=0,d=0;d<
b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%V.length},$b=a=>{var b=Zb(a.parent.id,a.name);if(V[b]===a)V[b]=a.lb;else for(b=V[b];b;){if(b.lb===a){b.lb=a.lb;break}b=b.lb}},Tb=(a,b)=>{var c;if(c=(c=ac(a,"x"))?c:a.Va.lookup?0:2)throw new R(c,a);for(c=V[Zb(a.id,b)];c;c=c.lb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Va.lookup(a,b)},Rb=(a,b,c,d)=>{a=new bc(a,b,c,d);b=Zb(a.parent.id,a.name);a.lb=V[b];return V[b]=a},cc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},dc=a=>{var b=
["r","w","rw"][a&3];a&512&&(b+="w");return b},ac=(a,b)=>{if(Xb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},ec=(a,b)=>{try{return Tb(a,b),20}catch(c){}return ac(a,"wx")},fc=(a,b,c)=>{try{var d=Tb(a,b)}catch(f){return f.Ya}if(a=ac(a,"wx"))return a;if(c){if(16384!==(d.mode&61440))return 54;if(d===d.parent||"/"===ja(d))return 10}else if(16384===(d.mode&61440))return 31;return 0},gc=(a=0,b=4096)=>{for(;a<=b;a++)if(!T[a])return a;
throw new R(33);},ic=(a,b)=>{hc||(hc=function(){},hc.prototype={});var c=new hc,d;for(d in a)c[d]=a[d];a=c;b=gc(b,void 0);a.fd=b;return T[b]=a},Qb={open:a=>{a.Wa=Vb[a.node.rdev].Wa;a.Wa.open&&a.Wa.open(a)},ib:()=>{throw new R(70);}},Kb=(a,b)=>{Vb[a]={Wa:b}},jc=(a,b)=>{var c="/"===b,d=!b;if(c&&Ub)throw new R(10);if(!c&&!d){var f=W(b,{Hb:!1});b=f.path;f=f.node;if(f.kb)throw new R(10);if(16384!==(f.mode&61440))throw new R(54);}b={type:a,dc:{},Kb:b,Wb:[]};a=a.fb(b);a.fb=b;b.root=a;c?Ub=a:f&&(f.kb=b,f.fb&&
f.fb.Wb.push(b))},la=(a,b,c)=>{var d=W(a,{parent:!0}).node;a=Eb(a);if(!a||"."===a||".."===a)throw new R(28);var f=ec(d,a);if(f)throw new R(f);if(!d.Va.pb)throw new R(63);return d.Va.pb(d,a,b,c)},X=(a,b)=>la(a,(void 0!==b?b:511)&1023|16384,0),kc=(a,b,c)=>{"undefined"===typeof c&&(c=b,b=438);la(a,b|8192,c)},lc=(a,b)=>{if(!Hb(a))throw new R(44);var c=W(b,{parent:!0}).node;if(!c)throw new R(44);b=Eb(b);var d=ec(c,b);if(d)throw new R(d);if(!c.Va.symlink)throw new R(63);c.Va.symlink(c,b,a)},Da=a=>{var b=
W(a,{parent:!0}).node;if(!b)throw new R(44);a=Eb(a);var c=Tb(b,a),d=fc(b,a,!1);if(d)throw new R(d);if(!b.Va.unlink)throw new R(63);if(c.kb)throw new R(10);b.Va.unlink(b,a);$b(c)},Yb=a=>{a=W(a).node;if(!a)throw new R(44);if(!a.Va.readlink)throw new R(28);return Hb(ja(a.parent),a.Va.readlink(a))},mc=(a,b)=>{a=W(a,{hb:!b}).node;if(!a)throw new R(44);if(!a.Va.cb)throw new R(63);return a.Va.cb(a)},nc=a=>mc(a,!0),ma=(a,b)=>{a="string"===typeof a?W(a,{hb:!0}).node:a;if(!a.Va.bb)throw new R(63);a.Va.bb(a,
{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},oc=a=>{a="string"===typeof a?W(a,{hb:!0}).node:a;if(!a.Va.bb)throw new R(63);a.Va.bb(a,{timestamp:Date.now()})},pc=(a,b)=>{if(0>b)throw new R(28);a="string"===typeof a?W(a,{hb:!0}).node:a;if(!a.Va.bb)throw new R(63);if(16384===(a.mode&61440))throw new R(31);if(32768!==(a.mode&61440))throw new R(28);var c=ac(a,"w");if(c)throw new R(c);a.Va.bb(a,{size:b,timestamp:Date.now()})},B=(a,b,c,d)=>{if(""===a)throw new R(44);if("string"===typeof b){var f=cc[b];
if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=A(a);try{g=W(a,{hb:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(g){if(b&128)throw new R(20);}else g=la(a,c,0),f=!0;if(!g)throw new R(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new R(54);if(!f&&(c=g?40960===(g.mode&61440)?32:16384===(g.mode&61440)&&("r"!==dc(b)||b&512)?31:ac(g,dc(b)):44))throw new R(c);b&
512&&pc(g,0);b&=-131713;d=ic({node:g,path:ja(g),flags:b,seekable:!0,position:0,Wa:g.Wa,ac:[],error:!1},d);d.Wa.open&&d.Wa.open(d);!e.logReadFiles||b&1||(qc||(qc={}),a in qc||(qc[a]=1));return d},oa=a=>{if(null===a.fd)throw new R(8);a.xb&&(a.xb=null);try{a.Wa.close&&a.Wa.close(a)}catch(b){throw b;}finally{T[a.fd]=null}a.fd=null},rc=(a,b,c)=>{if(null===a.fd)throw new R(8);if(!a.seekable||!a.Wa.ib)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.Wa.ib(a,b,c);a.ac=[]},sc=(a,b,c,d,f)=>
{if(0>d||0>f)throw new R(28);if(null===a.fd)throw new R(8);if(1===(a.flags&2097155))throw new R(8);if(16384===(a.node.mode&61440))throw new R(31);if(!a.Wa.read)throw new R(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new R(70);b=a.Wa.read(a,b,c,d,f);g||(a.position+=b);return b},na=(a,b,c,d,f,g)=>{if(0>d||0>f)throw new R(28);if(null===a.fd)throw new R(8);if(0===(a.flags&2097155))throw new R(8);if(16384===(a.node.mode&61440))throw new R(31);if(!a.Wa.write)throw new R(28);
a.seekable&&a.flags&1024&&rc(a,0,2);var m="undefined"!==typeof f;if(!m)f=a.position;else if(!a.seekable)throw new R(70);b=a.Wa.write(a,b,c,d,f,g);m||(a.position+=b);return b},Ca=a=>{var b="binary";if("utf8"!==b&&"binary"!==b)throw Error('Invalid encoding type "'+b+'"');var c;var d=B(a,d||0);a=mc(a).size;var f=new Uint8Array(a);sc(d,f,0,a,0);"utf8"===b?c=hb(f,0):"binary"===b&&(c=f);oa(d);return c},Tc=()=>{R||(R=function(a,b){this.node=b;this.$b=function(c){this.Ya=c};this.$b(a);this.message="FS error"},
R.prototype=Error(),R.prototype.constructor=R,[44].forEach(a=>{Sb[a]=new R(a);Sb[a].stack="<generic error, no stack>"}))},Uc,ka=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Wc=(a,b,c)=>{a=A("/dev/"+a);var d=ka(!!b,!!c);Vc||(Vc=64);var f=Vc++<<8|0;Kb(f,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,m,q,r)=>{for(var t=0,y=0;y<r;y++){try{var H=b()}catch(aa){throw new R(29);}if(void 0===H&&0===t)throw new R(6);if(null===H||void 0===H)break;t++;m[q+y]=H}t&&(g.node.timestamp=
Date.now());return t},write:(g,m,q,r)=>{for(var t=0;t<r;t++)try{c(m[q+t])}catch(y){throw new R(29);}r&&(g.node.timestamp=Date.now());return t}});kc(a,d,f)},Vc,Y={},hc,qc,Xc={};
function Yc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&A(b)!==A(ja(f.node)))return-54;throw f;}N(c|0,d.dev|0,4);N(c+4|0,0,4);N(c+8|0,d.ino|0,4);N(c+12|0,d.mode|0,4);N(c+16|0,d.nlink|0,4);N(c+20|0,d.uid|0,4);N(c+24|0,d.gid|0,4);N(c+28|0,d.rdev|0,4);N(c+32|0,0,4);N(c+40|0,d.size|0,8);N(c+48|0,4096,4);N(c+52|0,d.blocks|0,4);N(c+56|0,d.atime.getTime()/1E3|0,4);N(c+60|0,0,4);N(c+64|0,d.mtime.getTime()/1E3|0,4);N(c+68|0,0,4);N(c+72|0,d.ctime.getTime()/1E3|0,4);N(c+76|0,0,4);N(c+80|0,d.ino|0,8);return 0}
var Zc=void 0;function $c(){Zc+=4;return G(Zc-4|0,4,0)|0}function Z(a){a=T[a];if(!a)throw new R(8);return a}function ad(a,b,c){function d(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}var f=(new Date).getFullYear(),g=new Date(f,0,1),m=new Date(f,6,1);f=g.getTimezoneOffset();var q=m.getTimezoneOffset();N(a|0,60*Math.max(f,q)|0,4);N(b|0,Number(f!=q)|0,4);a=d(g);b=d(m);a=ib(a);b=ib(b);q<f?(N(c|0,a|0,4),N(c+4|0,b|0,4)):(N(c|0,b|0,4),N(c+4|0,a|0,4))}
function bd(a,b,c){bd.Qb||(bd.Qb=!0,ad(a,b,c))}var cd;cd=Ja?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var dd={};function ed(){if(!fd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:Ga||"./this.program"},b;for(b in dd)void 0===dd[b]?delete a[b]:a[b]=dd[b];var c=[];for(b in a)c.push(b+"="+a[b]);fd=c}return fd}var fd;
function bc(a,b,c,d){a||(a=this);this.parent=a;this.fb=a.fb;this.kb=null;this.id=Wb++;this.name=b;this.mode=c;this.Va={};this.Wa={};this.rdev=d}Object.defineProperties(bc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Tc();V=Array(4096);jc(S,"/");X("/tmp");X("/home");X("/home/web_user");
(()=>{X("/dev");Kb(259,{read:()=>0,write:(b,c,d,f)=>f});kc("/dev/null",259);Jb(1280,Mb);Jb(1536,Nb);kc("/dev/tty",1280);kc("/dev/tty1",1536);var a=Gb();Wc("random",a);Wc("urandom",a);X("/dev/shm");X("/dev/shm/tmp")})();(()=>{X("/proc");var a=X("/proc/self");X("/proc/self/fd");jc({fb:()=>{var b=Rb(a,"fd",16895,73);b.Va={lookup:(c,d)=>{var f=T[+d];if(!f)throw new R(8);c={parent:null,fb:{Kb:"fake"},Va:{readlink:()=>f.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
function wa(a,b){var c=Array(ia(a)+1);a=x(a,c,0,c.length);b&&(c.length=a);return c}
var hd={b:function(a,b,c,d){M("Assertion failed: "+I(a)+", at: "+[b?I(b):"unknown filename",c,d?I(d):"unknown function"])},m:function(a,b){try{a=I(a);if(b&-8)var c=-28;else{var d=W(a,{hb:!0}).node;d?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&ac(d,a)?-2:0):c=-44}return c}catch(f){if("undefined"===typeof Y||!(f instanceof R))throw f;return-f.Ya}},O:function(a,b){try{return a=I(a),ma(a,b),0}catch(c){if("undefined"===typeof Y||!(c instanceof R))throw c;return-c.Ya}},M:function(a){try{return a=
I(a),oc(a),0}catch(b){if("undefined"===typeof Y||!(b instanceof R))throw b;return-b.Ya}},k:function(a,b){try{var c=T[a];if(!c)throw new R(8);ma(c.node,b);return 0}catch(d){if("undefined"===typeof Y||!(d instanceof R))throw d;return-d.Ya}},N:function(a){try{var b=T[a];if(!b)throw new R(8);oc(b.node);return 0}catch(c){if("undefined"===typeof Y||!(c instanceof R))throw c;return-c.Ya}},d:function(a,b,c){Zc=c;try{var d=Z(a);switch(b){case 0:var f=$c();return 0>f?-28:B(d.path,d.flags,0,f).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return f=$c(),d.flags|=f,0;case 5:return f=$c(),N(f+0|0,2,2),0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return N(gd()|0,28,4),-1;default:return-28}}catch(g){if("undefined"===typeof Y||!(g instanceof R))throw g;return-g.Ya}},K:function(a,b){try{var c=Z(a);return Yc(mc,c.path,b)}catch(d){if("undefined"===typeof Y||!(d instanceof R))throw d;return-d.Ya}},H:function(a,b,c,d){try{b=I(b);var f=d&256;d&=4096;var g=b;if("/"===g[0])b=g;else{if(-100===a)var m="/";
else{var q=T[a];if(!q)throw new R(8);m=q.path}if(0==g.length){if(!d)throw new R(44);b=m}else b=A(m+"/"+g)}return Yc(f?nc:mc,b,c)}catch(r){if("undefined"===typeof Y||!(r instanceof R))throw r;return-r.Ya}},E:function(a,b){try{var c=T[a];if(!c)throw new R(8);if(0===(c.flags&2097155))throw new R(28);pc(c.node,b);return 0}catch(d){if("undefined"===typeof Y||!(d instanceof R))throw d;return-d.Ya}},D:function(a,b){try{if(0===b)return-28;if(b<ia("/")+1)return-68;x("/",w,a,b);return a}catch(c){if("undefined"===
typeof Y||!(c instanceof R))throw c;return-c.Ya}},A:function(){return 0},L:function(a,b,c){Zc=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=$c();N(f|0,0,4);return 0;case 21520:return d.tty?-28:-59;case 21531:a=f=$c();if(!d.Wa.Tb)throw new R(59);return d.Wa.Tb(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:M("bad ioctl syscall "+
b)}}catch(g){if("undefined"===typeof Y||!(g instanceof R))throw g;return-g.Ya}},G:function(a,b){try{return a=I(a),Yc(nc,a,b)}catch(c){if("undefined"===typeof Y||!(c instanceof R))throw c;return-c.Ya}},w:function(a,b){try{return a=I(a),a=A(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),X(a,b),0}catch(c){if("undefined"===typeof Y||!(c instanceof R))throw c;return-c.Ya}},v:function(a,b,c,d,f,g){try{a:{g<<=12;var m=!1;if(0!==(d&16)&&0!==a%65536)var q=-28;else{if(0!==(d&32)){var r=Ob(b);if(!r){q=-48;
break a}m=!0}else{var t=T[f];if(!t){q=-8;break a}var y=g;if(0!==(c&2)&&0===(d&2)&&2!==(t.flags&2097155))throw new R(2);if(1===(t.flags&2097155))throw new R(2);if(!t.Wa.qb)throw new R(43);var H=t.Wa.qb(t,a,b,y,c,d);r=H.Yb;m=H.tb}Xc[r]={Vb:r,Ub:b,tb:m,fd:f,Xb:c,flags:d,offset:g};q=r}}return q}catch(aa){if("undefined"===typeof Y||!(aa instanceof R))throw aa;return-aa.Ya}},u:function(a,b){try{var c=Xc[a];if(0!==b&&c){if(b===c.Ub){var d=T[c.fd];if(d&&c.Xb&2){var f=c.flags,g=c.offset,m=w.slice(a,a+b);d&&
d.Wa.rb&&d.Wa.rb(d,m,g,b,f)}Xc[a]=null;c.tb&&ha(c.Vb)}var q=0}else q=-28;return q}catch(r){if("undefined"===typeof Y||!(r instanceof R))throw r;return-r.Ya}},j:function(a,b,c){Zc=c;try{var d=I(a),f=c?$c():0;return B(d,b,f).fd}catch(g){if("undefined"===typeof Y||!(g instanceof R))throw g;return-g.Ya}},t:function(a,b,c){try{a=I(a);if(0>=c)var d=-28;else{var f=Yb(a),g=Math.min(c,ia(f)),m=G(b+g,1,0);x(f,w,b,c+1);N(b+g,m,1);d=g}return d}catch(q){if("undefined"===typeof Y||!(q instanceof R))throw q;return-q.Ya}},
s:function(a){try{a=I(a);var b=W(a,{parent:!0}).node,c=Eb(a),d=Tb(b,c),f=fc(b,c,!0);if(f)throw new R(f);if(!b.Va.rmdir)throw new R(63);if(d.kb)throw new R(10);b.Va.rmdir(b,c);$b(d);return 0}catch(g){if("undefined"===typeof Y||!(g instanceof R))throw g;return-g.Ya}},J:function(a,b){try{return a=I(a),Yc(mc,a,b)}catch(c){if("undefined"===typeof Y||!(c instanceof R))throw c;return-c.Ya}},q:function(a){try{return a=I(a),Da(a),0}catch(b){if("undefined"===typeof Y||!(b instanceof R))throw b;return-b.Ya}},
g:function(){M("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},l:function(){M("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},y:function(a,b){a=new Date(1E3*(G(a|0,4,0)|0));N(b|0,a.getSeconds()|0,4);N(b+4|0,a.getMinutes()|0,4);N(b+8|0,a.getHours()|0,4);N(b+12|0,a.getDate()|0,4);N(b+16|0,a.getMonth()|0,4);N(b+20|0,a.getFullYear()-1900|0,4);
N(b+24|0,a.getDay()|0,4);var c=new Date(a.getFullYear(),0,1);N(b+28|0,(a.getTime()-c.getTime())/864E5|0,4);N(b+36|0,-(60*a.getTimezoneOffset())|0,4);var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();N(b+32|0,(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0,4)},z:bd,o:function(){M("")},c:function(){M("alignment fault")},r:function(){return 2147483648},h:cd,n:function(a){var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{db.grow(Math.min(2147483648,d)-jb.byteLength+65535>>>16);kb();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},B:function(a,b){var c=0;ed().forEach(function(d,f){var g=b+c;N(a+4*f|0,g|0,4);f=g;for(g=0;g<d.length;++g)N(f++|0,d.charCodeAt(g)|0,1);N(f|0,0,1);c+=d.length+1});return 0},C:function(a,b){var c=ed();N(a|0,c.length|0,4);var d=0;c.forEach(function(f){d+=f.length+1});N(b|0,d|0,4);return 0},e:function(a){try{var b=Z(a);
oa(b);return 0}catch(c){if("undefined"===typeof Y||!(c instanceof R))throw c;return c.Ya}},p:function(a,b){try{var c=Z(a);N(b|0,(c.tty?2:16384===(c.mode&61440)?3:40960===(c.mode&61440)?7:4)|0,1);return 0}catch(d){if("undefined"===typeof Y||!(d instanceof R))throw d;return d.Ya}},i:function(a,b,c,d){try{a:{for(var f=Z(a),g=a=0;g<c;g++){var m=G(b+8*g|0,4,0)|0,q=G(b+(8*g+4)|0,4,0)|0,r=sc(f,J,m,q,void 0);if(0>r){var t=-1;break a}a+=r;if(r<q)break}t=a}N(d|0,t|0,4);return 0}catch(y){if("undefined"===typeof Y||
!(y instanceof R))throw y;return y.Ya}},x:function(a,b,c,d){try{var f=Number(b&BigInt(4294967295))|0,g=Number(b>>BigInt(32))|0,m=Z(a);a=4294967296*g+(f>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;rc(m,a,c);N(d|0,m.position|0,8);m.xb&&0===a&&0===c&&(m.xb=null);return 0}catch(q){if("undefined"===typeof Y||!(q instanceof R))throw q;return q.Ya}},F:function(a){try{var b=Z(a);return b.Wa&&b.Wa.fsync?-b.Wa.fsync(b):0}catch(c){if("undefined"===typeof Y||!(c instanceof R))throw c;return c.Ya}},
f:function(a,b,c,d){try{a:{for(var f=Z(a),g=a=0;g<c;g++){var m=G(b+8*g|0,4,0)|0,q=G(b+(8*g+4)|0,4,0)|0,r=na(f,J,m,q,void 0);if(0>r){var t=-1;break a}a+=r}t=a}N(d|0,t|0,4);return 0}catch(y){if("undefined"===typeof Y||!(y instanceof R))throw y;return y.Ya}},I:function(a){var b=Date.now();N(a|0,b/1E3|0,4);N(a+4|0,b%1E3*1E3|0,4);return 0},a:function(){M("segmentation fault")},P:function(a){var b=Date.now()/1E3|0;a&&N(a|0,b|0,4);return b},Q:function(a,b){if(b){var c=b+8;b=1E3*(G(c|0,4,0)|0);b+=(G(c+4|
0,4,0)|0)/1E3}else b=Date.now();a=I(a);try{var d=W(a,{hb:!0}).node;d.Va.bb(d,{timestamp:Math.max(b,b)});var f=0}catch(g){if(!(g instanceof R)){b:{f=Error();if(!f.stack){try{throw Error();}catch(m){f=m}if(!f.stack){f="(no stack trace available)";break b}}f=f.stack.toString()}e.extraStackTrace&&(f+="\n"+e.extraStackTrace());f=xb(f);throw g+" : "+f;}f=g.Ya;N(gd()|0,f|0,4);f=-1}return f}};
(function(){function a(f){e.asm=f.exports;db=e.asm.R;kb();L=e.asm.Oa;mb.unshift(e.asm.S);pb--;e.monitorRunDependencies&&e.monitorRunDependencies(pb);0==pb&&(null!==qb&&(clearInterval(qb),qb=null),rb&&(f=rb,rb=null,f()))}function b(f){a(f.instance)}function c(f){return vb().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(f,function(g){Qa("failed to asynchronously prepare wasm: "+g);M(g)})}var d={a:hd};pb++;e.monitorRunDependencies&&e.monitorRunDependencies(pb);
if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return Qa("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Ta||"function"!==typeof WebAssembly.instantiateStreaming||sb()||O.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){Qa("wasm streaming compile failed: "+g);Qa("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.S).apply(null,arguments)};e._sqlite3_free=function(){return(e._sqlite3_free=e.asm.T).apply(null,arguments)};e._sqlite3_prepare_v2=function(){return(e._sqlite3_prepare_v2=e.asm.U).apply(null,arguments)};e._sqlite3_step=function(){return(e._sqlite3_step=e.asm.V).apply(null,arguments)};e._sqlite3_finalize=function(){return(e._sqlite3_finalize=e.asm.W).apply(null,arguments)};
e._sqlite3_reset=function(){return(e._sqlite3_reset=e.asm.X).apply(null,arguments)};e._sqlite3_clear_bindings=function(){return(e._sqlite3_clear_bindings=e.asm.Y).apply(null,arguments)};e._sqlite3_value_blob=function(){return(e._sqlite3_value_blob=e.asm.Z).apply(null,arguments)};e._sqlite3_value_text=function(){return(e._sqlite3_value_text=e.asm._).apply(null,arguments)};e._sqlite3_value_bytes=function(){return(e._sqlite3_value_bytes=e.asm.$).apply(null,arguments)};
e._sqlite3_value_double=function(){return(e._sqlite3_value_double=e.asm.aa).apply(null,arguments)};e._sqlite3_value_int=function(){return(e._sqlite3_value_int=e.asm.ba).apply(null,arguments)};e._sqlite3_value_type=function(){return(e._sqlite3_value_type=e.asm.ca).apply(null,arguments)};e._sqlite3_result_blob=function(){return(e._sqlite3_result_blob=e.asm.da).apply(null,arguments)};e._sqlite3_result_double=function(){return(e._sqlite3_result_double=e.asm.ea).apply(null,arguments)};
e._sqlite3_result_error=function(){return(e._sqlite3_result_error=e.asm.fa).apply(null,arguments)};e._sqlite3_result_int=function(){return(e._sqlite3_result_int=e.asm.ga).apply(null,arguments)};e._sqlite3_result_int64=function(){return(e._sqlite3_result_int64=e.asm.ha).apply(null,arguments)};e._sqlite3_result_null=function(){return(e._sqlite3_result_null=e.asm.ia).apply(null,arguments)};e._sqlite3_result_text=function(){return(e._sqlite3_result_text=e.asm.ja).apply(null,arguments)};
e._sqlite3_column_count=function(){return(e._sqlite3_column_count=e.asm.ka).apply(null,arguments)};e._sqlite3_data_count=function(){return(e._sqlite3_data_count=e.asm.la).apply(null,arguments)};e._sqlite3_column_blob=function(){return(e._sqlite3_column_blob=e.asm.ma).apply(null,arguments)};e._sqlite3_column_bytes=function(){return(e._sqlite3_column_bytes=e.asm.na).apply(null,arguments)};e._sqlite3_column_double=function(){return(e._sqlite3_column_double=e.asm.oa).apply(null,arguments)};
e._sqlite3_column_text=function(){return(e._sqlite3_column_text=e.asm.pa).apply(null,arguments)};e._sqlite3_column_type=function(){return(e._sqlite3_column_type=e.asm.qa).apply(null,arguments)};e._sqlite3_column_name=function(){return(e._sqlite3_column_name=e.asm.ra).apply(null,arguments)};e._sqlite3_bind_blob=function(){return(e._sqlite3_bind_blob=e.asm.sa).apply(null,arguments)};e._sqlite3_bind_double=function(){return(e._sqlite3_bind_double=e.asm.ta).apply(null,arguments)};
e._sqlite3_bind_int=function(){return(e._sqlite3_bind_int=e.asm.ua).apply(null,arguments)};e._sqlite3_bind_text=function(){return(e._sqlite3_bind_text=e.asm.va).apply(null,arguments)};e._sqlite3_bind_parameter_index=function(){return(e._sqlite3_bind_parameter_index=e.asm.wa).apply(null,arguments)};e._sqlite3_sql=function(){return(e._sqlite3_sql=e.asm.xa).apply(null,arguments)};e._sqlite3_normalized_sql=function(){return(e._sqlite3_normalized_sql=e.asm.ya).apply(null,arguments)};
e._sqlite3_exec=function(){return(e._sqlite3_exec=e.asm.za).apply(null,arguments)};e._sqlite3_errmsg=function(){return(e._sqlite3_errmsg=e.asm.Aa).apply(null,arguments)};e._sqlite3_changes=function(){return(e._sqlite3_changes=e.asm.Ba).apply(null,arguments)};e._sqlite3_close_v2=function(){return(e._sqlite3_close_v2=e.asm.Ca).apply(null,arguments)};e._sqlite3_create_function_v2=function(){return(e._sqlite3_create_function_v2=e.asm.Da).apply(null,arguments)};
e._sqlite3_open=function(){return(e._sqlite3_open=e.asm.Ea).apply(null,arguments)};
var ha=e._free=function(){return(ha=e._free=e.asm.Fa).apply(null,arguments)},v=e._malloc=function(){return(v=e._malloc=e.asm.Ga).apply(null,arguments)},gd=e.___errno_location=function(){return(gd=e.___errno_location=e.asm.Ha).apply(null,arguments)},qa=e._dbClose=function(){return(qa=e._dbClose=e.asm.Ia).apply(null,arguments)},ra=e._dbExec=function(){return(ra=e._dbExec=e.asm.Ja).apply(null,arguments)},sa=e._dbMemoryLoadOrSave=function(){return(sa=e._dbMemoryLoadOrSave=e.asm.Ka).apply(null,arguments)},
ta=e._dbNoop=function(){return(ta=e._dbNoop=e.asm.La).apply(null,arguments)},ua=e._dbOpen=function(){return(ua=e._dbOpen=e.asm.Ma).apply(null,arguments)},va=e._dbTableInsert=function(){return(va=e._dbTableInsert=e.asm.Na).apply(null,arguments)},bb=e._sbrk=function(){return(bb=e._sbrk=e.asm.Pa).apply(null,arguments)},Pb=e._memalign=function(){return(Pb=e._memalign=e.asm.Qa).apply(null,arguments)},cb=e._emscripten_stack_get_base=function(){return(cb=e._emscripten_stack_get_base=e.asm.Ra).apply(null,
arguments)},xa=e.stackSave=function(){return(xa=e.stackSave=e.asm.Sa).apply(null,arguments)},Aa=e.stackRestore=function(){return(Aa=e.stackRestore=e.asm.Ta).apply(null,arguments)},F=e.stackAlloc=function(){return(F=e.stackAlloc=e.asm.Ua).apply(null,arguments)};e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?e["_"+a]:function(){return fb(a,b,c,arguments)}};e.UTF8ToString=I;e.stackSave=xa;e.stackRestore=Aa;e.stackAlloc=F;var jd;
rb=function kd(){jd||ld();jd||(rb=kd)};
function ld(){function a(){if(!jd&&(jd=!0,e.calledRun=!0,!eb)){$a=!0;e.noFSInit||Uc||(Uc=!0,Tc(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?Wc("stdin",e.stdin):lc("/dev/tty","/dev/stdin"),e.stdout?Wc("stdout",null,e.stdout):lc("/dev/tty","/dev/stdout"),e.stderr?Wc("stderr",null,e.stderr):lc("/dev/tty1","/dev/stderr"),B("/dev/stdin",0),B("/dev/stdout",1),B("/dev/stderr",1));Xb=!1;wb(mb);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&
(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();nb.unshift(b)}wb(nb)}}if(!(0<pb)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ob();wb(lb);0<pb||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=ld;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();ld();

}());
/*jslint-enable*/
