
/*jslint-disable*/
(function () {
    "use strict";

var e;e||(e=typeof Module !== 'undefined' ? Module : {});var ba=Object.assign;null;let k={},n,ca,ea=da("sqlite3_errmsg","string",["number"]),fa;
function ha(a){function b(p){null!=n&&n.close();return n=new fa.Database(p)}let c=a.argList,d=new Uint8Array(a.baton&&a.baton.buffer);var f=0,g=a.cFuncName;let m=f=0,q="";var r=a.id;switch(g){case "_dbClose":case "_dbExec":case "_dbMemoryLoadOrSave":case "_dbNoop":case "_dbOpen":case "_dbTableInsert":f=t(d.byteLength);a.batonPtr=f;x.set(d,f);k[g](f);q=ia(f+272);d.set(new Uint8Array(x.buffer,x.byteOffset+f,1024));d=new BigInt64Array(d.buffer,8);d.subarray(16,32).forEach(function(p,w){p=Number(p);0===
p?c[w]=d[w]:(c[w]=new ArrayBuffer(Number(d[w])),(new Uint8Array(c[w])).set(x.subarray(p,p+c[w].byteLength)))});if(!q&&"_dbOpen"===g&&c[4]){f=Number(c[0]);ja("/tmp/__dbTmp",c[4]);try{(m=ka(f,"/tmp/__dbTmp",0))&&(q=ea(f))}finally{la("/tmp/__dbTmp")}}postMessage({argList:c,baton:new DataView(d.buffer),cFuncName:g,errmsg:q,id:r},[d.buffer,...c.filter(function(p){return p&&p.constructor===ArrayBuffer})]);return}g=a.sql;switch(a.action){case "open":return a=a.buffer,b(a&&new Uint8Array(a)),postMessage({id:r,
rawPtr:n.db,ready:!0});case "exec":null===n&&b();if(!g)throw"exec: Missing query string";return postMessage({id:r,results:n.exec(g,a.params)});case "export":a=n["export"]();r={id:r,buffer:a};try{return postMessage(r,[r])}catch(p){return postMessage(r)}case "close":return n&&n.close(),postMessage({id:r});default:throw Error("Invalid action : "+a.action);}}self.onmessage=async function({data:a}){fa=fa||await ca;a.batonPtr=0;try{await ha(a)}catch(b){postMessage({id:a.id,errmsg:b.message})}finally{ma(a.batonPtr)}};
ca=new Promise(function(a){e.postRun=a});
e.onRuntimeInitialized=function(){function a(h,l){this.ab=h;this.db=l;this.$a=1;this.vb=[]}function b(h,l){this.db=l;l=y(h)+1;this.ob=t(l);if(null===this.ob)throw Error("Unable to allocate memory for the SQL string");z(h,x,this.ob,l);this.tb=this.ob;this.kb=this.zb=null}function c(h){this.filename="/tmp/dbfile1";null!=h&&ja(this.filename,h);this.handleError(g(this.filename,d));this.db=A(d,"i32");this.pb={};this.hb={}}let d=E(4),f=e.cwrap;f("__dbMemoryLoadOrSave","number",["number","string","number"]);
k._dbClose=na;k._dbExec=pa;k._dbMemoryLoadOrSave=qa;k._dbNoop=ra;k._dbOpen=sa;k._dbTableInsert=ta;ea=f("sqlite3_errmsg","string",["number"]);let g=f("sqlite3_open","number",["string","number"]),m=f("sqlite3_close_v2","number",["number"]),q=f("sqlite3_exec","number",["number","string","number","number","number"]),r=f("sqlite3_changes","number",["number"]),p=f("sqlite3_prepare_v2","number",["number","string","number","number","number"]),w=f("sqlite3_sql","string",["number"]),H=f("sqlite3_normalized_sql",
"string",["number"]),Z=f("sqlite3_prepare_v2","number",["number","number","number","number","number"]),wc=f("sqlite3_bind_text","number",["number","number","number","number","number"]),Cb=f("sqlite3_bind_blob","number",["number","number","number","number","number"]),xc=f("sqlite3_bind_double","number",["number","number","number"]),yc=f("sqlite3_bind_int","number",["number","number","number"]),zc=f("sqlite3_bind_parameter_index","number",["number","string"]),Ac=f("sqlite3_step","number",["number"]),
Bc=f("sqlite3_column_count","number",["number"]),Cc=f("sqlite3_data_count","number",["number"]),Dc=f("sqlite3_column_double","number",["number","number"]),Db=f("sqlite3_column_text","string",["number","number"]),Ec=f("sqlite3_column_blob","number",["number","number"]),Fc=f("sqlite3_column_bytes","number",["number","number"]),Gc=f("sqlite3_column_type","number",["number","number"]),Hc=f("sqlite3_column_name","string",["number","number"]),Ic=f("sqlite3_reset","number",["number"]),Jc=f("sqlite3_clear_bindings",
"number",["number"]),Kc=f("sqlite3_finalize","number",["number"]),Lc=f("sqlite3_create_function_v2","number","number string number number number number number number number".split(" ")),Mc=f("sqlite3_value_type","number",["number"]),Nc=f("sqlite3_value_bytes","number",["number"]),Oc=f("sqlite3_value_text","string",["number"]),Pc=f("sqlite3_value_blob","number",["number"]),Qc=f("sqlite3_value_double","number",["number"]),Rc=f("sqlite3_result_double","",["number","number"]),Eb=f("sqlite3_result_null",
"",["number"]),Sc=f("sqlite3_result_text","",["number","string","number","number"]),Tc=f("sqlite3_result_blob","",["number","number","number","number"]),Uc=f("sqlite3_result_int","",["number","number"]),Fb=f("sqlite3_result_error","",["number","string","number"]);a.prototype.bind=function(h){if(!this.ab)throw"Statement closed";this.reset();return Array.isArray(h)?this.Nb(h):null!=h&&"object"===typeof h?this.Ob(h):!0};a.prototype.step=function(){if(!this.ab)throw"Statement closed";this.$a=1;let h=
Ac(this.ab);switch(h){case 100:return!0;case 101:return!1;default:throw this.db.handleError(h);}};a.prototype.Jb=function(h){null==h&&(h=this.$a,this.$a+=1);return Dc(this.ab,h)};a.prototype.Tb=function(h){null==h&&(h=this.$a,this.$a+=1);h=Db(this.ab,h);if("function"!==typeof BigInt)throw Error("BigInt is not supported");return BigInt(h)};a.prototype.Ub=function(h){null==h&&(h=this.$a,this.$a+=1);return Db(this.ab,h)};a.prototype.getBlob=function(h){null==h&&(h=this.$a,this.$a+=1);let l=Fc(this.ab,
h);h=Ec(this.ab,h);let u=new Uint8Array(l);for(let v=0;v<l;v+=1)u[v]=F(h+v,1,0);return u};a.prototype.get=function(h,l){l=l||{};null!=h&&this.bind(h)&&this.step();h=[];let u=Cc(this.ab);for(let v=0;v<u;v+=1)switch(Gc(this.ab,v)){case 1:let C=l.useBigInt?this.Tb(v):this.Jb(v);h.push(C);break;case 2:h.push(this.Jb(v));break;case 3:h.push(this.Ub(v));break;case 4:h.push(this.getBlob(v));break;default:h.push(null)}return h};a.prototype.getColumnNames=function(){let h=[],l=Bc(this.ab);for(let u=0;u<l;u+=
1)h.push(Hc(this.ab,u));return h};a.prototype.getAsObject=function(h,l){h=this.get(h,l);l=this.getColumnNames();let u={};for(let v=0;v<l.length;v+=1)u[l[v]]=h[v];return u};a.prototype.getSQL=function(){return w(this.ab)};a.prototype.getNormalizedSQL=function(){return H(this.ab)};a.prototype.run=function(h){null!=h&&this.bind(h);this.step();return this.reset()};a.prototype.Eb=function(h,l){null==l&&(l=this.$a,this.$a+=1);h=ua(h);let u=t(h.length);this.vb.push(u);this.db.handleError(wc(this.ab,l,u,
h.length-1,0))};a.prototype.Mb=function(h,l){null==l&&(l=this.$a,this.$a+=1);let u=t(h.length);this.vb.push(u);this.db.handleError(Cb(this.ab,l,u,h.length,0))};a.prototype.Db=function(h,l){null==l&&(l=this.$a,this.$a+=1);this.db.handleError((h===(h|0)?yc:xc)(this.ab,l,h))};a.prototype.Pb=function(h){null==h&&(h=this.$a,this.$a+=1);Cb(this.ab,h,0,0,0)};a.prototype.Fb=function(h,l){null==l&&(l=this.$a,this.$a+=1);switch(typeof h){case "string":this.Eb(h,l);return;case "number":this.Db(h,l);return;case "bigint":this.Eb(h.toString(),
l);return;case "boolean":this.Db(h+0,l);return;case "object":if(null===h){this.Pb(l);return}if(null!=h.length){this.Mb(h,l);return}}throw"Wrong API use : tried to bind a value of an unknown type ("+h+").";};a.prototype.Ob=function(h){let l=this;Object.keys(h).forEach(function(u){let v=zc(l.ab,u);0!==v&&l.Fb(h[u],v)});return!0};a.prototype.Nb=function(h){for(let l=0;l<h.length;l+=1)this.Fb(h[l],l+1);return!0};a.prototype.reset=function(){this.freemem();return 0===Jc(this.ab)&&0===Ic(this.ab)};a.prototype.freemem=
function(){let h;for(;void 0!==(h=this.vb.pop());)ma(h)};a.prototype.free=function(){let h;this.freemem();h=0===Kc(this.ab);delete this.db.pb[this.ab];this.ab=0;return h};b.prototype.next=function(){if(null===this.ob)return{done:!0};null!==this.kb&&(this.kb.free(),this.kb=null);if(!this.db.db)throw this.xb(),Error("Database closed");let h=wa(),l=E(4);xa(d,0,"i32");xa(l,0,"i32");try{this.db.handleError(Z(this.db.db,this.tb,-1,d,l));this.tb=A(l,"i32");let u=A(d,"i32");if(0===u)return this.xb(),{done:!0};
this.kb=new a(u,this.db);this.db.pb[u]=this.kb;return{value:this.kb,done:!1}}catch(u){throw this.zb=G(this.tb),this.xb(),u;}finally{ya(h)}};b.prototype.xb=function(){ma(this.ob);this.ob=null};b.prototype.getRemainingSQL=function(){return null!==this.zb?this.zb:G(this.tb)};"function"===typeof Symbol&&"symbol"===typeof Symbol.iterator&&(b.prototype[Symbol.iterator]=function(){return this});c.prototype.run=function(h,l){if(!this.db)throw"Database closed";if(l){h=this.prepare(h,l);try{h.step()}finally{h.free()}}else this.handleError(q(this.db,
h,0,0,d));return this};c.prototype.exec=function(h,l,u){if(!this.db)throw"Database closed";let v=wa(),C=null;try{var aa=y(h)+1,B=E(aa);z(h,I,B,aa);h=B;let T=E(4);for(aa=[];0!==A(h,"i8");){xa(d,0,"i32");xa(T,0,"i32");this.handleError(Z(this.db,h,-1,d,T));let D=A(d,"i32");h=A(T,"i32");if(0!==D){B=null;C=new a(D,this);for(null!=l&&C.bind(l);C.step();)null===B&&(B={columns:C.getColumnNames(),values:[]},aa.push(B)),B.values.push(C.get(null,u));C.free()}}return aa}catch(T){throw C&&C.free(),T;}finally{ya(v)}};
c.prototype.each=function(h,l,u,v,C){"function"===typeof l&&(v=u,u=l,l=void 0);h=this.prepare(h,l);try{for(;h.step();)u(h.getAsObject(null,C))}finally{h.free()}if("function"===typeof v)return v()};c.prototype.prepare=function(h,l){xa(d,0,"i32");this.handleError(p(this.db,h,-1,d,0));h=A(d,"i32");if(0===h)throw"Nothing to prepare";let u=new a(h,this);null!=l&&u.bind(l);return this.pb[h]=u};c.prototype.iterateStatements=function(h){return new b(h,this)};c.prototype["export"]=function(){Object.values(this.pb).forEach(function(l){l.free()});
Object.values(this.hb).forEach(za);this.hb={};this.handleError(m(this.db));let h=Aa(this.filename);this.handleError(g(this.filename,d));this.db=A(d,"i32");return h};c.prototype.close=function(){null!==this.db&&(Object.values(this.pb).forEach(function(h){h.free()}),Object.values(this.hb).forEach(za),this.hb={},this.handleError(m(this.db)),la("/"+this.filename),this.db=null)};c.prototype.handleError=function(h){if(0===h)return null;h=ea(this.db);throw Error(h);};c.prototype.getRowsModified=function(){return r(this.db)};
c.prototype.create_function=function(h,l){Object.prototype.hasOwnProperty.call(this.hb,h)&&(za(this.hb[h]),delete this.hb[h]);let u=Ba(function(v,C,aa){let B,T=[];for(let oa=0;oa<C;oa+=1){var D=A(aa+4*oa,"i32"),P=Mc(D);if(1===P||2===P)D=Qc(D);else if(3===P)D=Oc(D);else if(4===P){P=D;D=Nc(P);P=Pc(P);let Hb=new Uint8Array(D);for(let va=0;va<D;va+=1)Hb[va]=F(P+va,1,0);D=Hb}else D=null;T.push(D)}try{B=l.apply(null,T)}catch(oa){Fb(v,oa,-1);return}switch(typeof B){case "boolean":Uc(v,B?1:0);break;case "number":Rc(v,
B);break;case "string":Sc(v,B,-1,-1);break;case "object":null===B?Eb(v):null!=B.length?(C=t(B.length),Tc(v,C,B.length,-1),ma(C)):Fb(v,"Wrong API use : tried to return a value of an unknown type ("+B+").",-1);break;default:Eb(v)}});this.hb[h]=u;this.handleError(Lc(this.db,h,l.length,1,0,u,0,0,0));return this};e.Database=c};
var Ca=ba({},e),Da="./this.program",Ea="object"===typeof window,Fa="function"===typeof importScripts,Ga="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,J="",Ha,Ia,Ja,fs,Ka,La;
if(Ga)J=Fa?require("path").dirname(J)+"/":__dirname+"/",La=()=>{Ka||(fs=require("fs"),Ka=require("path"))},Ha=function(a,b){La();a=Ka.normalize(a);return fs.readFileSync(a,b?null:"utf8")},Ja=a=>{a=Ha(a,!0);a.buffer||(a=new Uint8Array(a));return a},Ia=(a,b,c)=>{La();a=Ka.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(Da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),e.inspect=function(){return"[Emscripten Module object]"};
else if(Ea||Fa)Fa?J=self.location.href:"undefined"!==typeof document&&document.currentScript&&(J=document.currentScript.src),J=0!==J.indexOf("blob:")?J.substr(0,J.replace(/[?#].*/,"").lastIndexOf("/")+1):"",Ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},Fa&&(Ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),Ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var Ma=e.print||console.log.bind(console),Na=e.printErr||console.warn.bind(console);ba(e,Ca);Ca=null;e.thisProgram&&(Da=e.thisProgram);var Oa=[],Pa;
function Ba(a){if(!Pa){Pa=new WeakMap;for(var b=K.length,c=0;c<0+b;c++){var d=K.get(c);d&&Pa.set(d,c)}}if(Pa.has(a))return Pa.get(a);if(Oa.length)b=Oa.pop();else{try{K.grow(1)}catch(g){if(!(g instanceof RangeError))throw g;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}b=K.length-1}try{K.set(b,a)}catch(g){if(!(g instanceof TypeError))throw g;if("function"===typeof WebAssembly.Function){d={i:"i32",j:"i64",f:"f32",d:"f64"};var f={parameters:[],results:[]};for(c=1;4>c;++c)f.parameters.push(d["viii"[c]]);
c=new WebAssembly.Function(f,a)}else{d=[1,0,1,96];f={i:127,j:126,f:125,d:124};d.push(3);for(c=0;3>c;++c)d.push(f["iii"[c]]);d.push(0);d[1]=d.length-2;c=new Uint8Array([0,97,115,109,1,0,0,0].concat(d,[2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0]));c=new WebAssembly.Module(c);c=(new WebAssembly.Instance(c,{e:{f:a}})).exports.f}K.set(b,c)}Pa.set(a,b);return b}function za(a){Pa.delete(K.get(a));Oa.push(a)}var Qa;e.wasmBinary&&(Qa=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;
"object"!==typeof WebAssembly&&L("no native wasm support detected");
function xa(a,b,c="i8",d){"*"===c.charAt(c.length-1)&&(c="i32");if(d)switch(c){case "i1":I[a>>0]=b;break;case "i8":I[a>>0]=b;break;case "i16":Ra[a>>1]=b;break;case "i32":Sa[a>>2]=b;break;case "i64":Ta[a>>3]=BigInt(b);break;case "float":Ua[a>>2]=b;break;case "double":Va[a>>3]=b;break;default:L("invalid type for setValue: "+c)}else switch(c){case "i1":M(a|0,b|0,1);break;case "i8":M(a|0,b|0,1);break;case "i16":M(a|0,b|0,2);break;case "i32":M(a|0,b|0,4);break;case "i64":M(a|0,b|0,8);break;case "float":b=
Math.fround(b);M(a|0,b,4,!0);break;case "double":M(a|0,+b,8,!0);break;default:L("invalid type for setValue: "+c)}}
function A(a,b="i8",c){"*"===b.charAt(b.length-1)&&(b="i32");if(c)switch(b){case "i1":return I[a>>0];case "i8":return I[a>>0];case "i16":return Ra[a>>1];case "i32":return Sa[a>>2];case "i64":return Number(Ta[a>>3]);case "float":return Ua[a>>2];case "double":return Number(Va[a>>3]);default:L("invalid type for getValue: "+b)}else switch(b){case "i1":return F(a|0,1,0)|0;case "i8":return F(a|0,1,0)|0;case "i16":return F(a|0,2,0)|0;case "i32":return F(a|0,4,0)|0;case "i64":return F(a|0,8,0)|0;case "float":return Math.fround(F(a|
0,4,0,!0));case "double":return+F(a|0,8,0,!0);default:L("invalid type for getValue: "+b)}return null}function Wa(a,b){switch(a){case 1:return"i8";case 2:return"i16";case 4:return b?"float":"i32";case 8:return b?"double":"i64";default:L(void 0)}}
function M(a,b,c,d){0>=a&&L("segmentation fault storing "+c+" bytes to address "+a);0!==a%c&&L("alignment error storing to address "+a+", which was expected to be aligned to a multiple of "+c);if(Xa&&!Ya){var f=Za()>>>0;a+c>f&&L("segmentation fault, exceeded the top of the available dynamic heap when storing "+c+" bytes to address "+a+". DYNAMICTOP="+f);f>=$a()||L(void 0);f<=I.length||L(void 0)}xa(a,b,Wa(c,d),1)}
function F(a,b,c,d){0>=a&&L("segmentation fault loading "+b+" bytes from address "+a);0!==a%b&&L("alignment error loading from address "+a+", which was expected to be aligned to a multiple of "+b);if(Xa&&!Ya){var f=Za()>>>0;a+b>f&&L("segmentation fault, exceeded the top of the available dynamic heap when loading "+b+" bytes from address "+a+". DYNAMICTOP="+f);f>=$a()||L(void 0);f<=I.length||L(void 0)}b=Wa(b,d);a=A(a,b,1);c&&(c=parseInt(b.substr(1),10),a=0<=a?a:32>=c?2*Math.abs(1<<c-1)+a:Math.pow(2,
c)+a);return a}var ab,bb=!1;function cb(a,b,c,d){var f={string:function(p){var w=0;if(null!==p&&void 0!==p&&0!==p){var H=(p.length<<2)+1;w=E(H);z(p,x,w,H)}return w},array:function(p){var w=E(p.length);I.set(p,w);return w}};a=e["_"+a];var g=[],m=0;if(d)for(var q=0;q<d.length;q++){var r=f[c[q]];r?(0===m&&(m=wa()),g[q]=r(d[q])):g[q]=d[q]}c=a.apply(null,g);return c=function(p){0!==m&&ya(m);return"string"===b?G(p):"boolean"===b?!!p:p}(c)}
function da(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?e["_"+a]:function(){return cb(a,b,c,arguments)}}var db="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function eb(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&db)return db.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var m=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|m:(f&7)<<18|g<<12|m<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function G(a,b){return a?eb(x,a,b):""}
function z(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var m=a.charCodeAt(g);if(55296<=m&&57343>=m){var q=a.charCodeAt(++g);m=65536+((m&1023)<<10)|q&1023}if(127>=m){if(c>=d)break;b[c++]=m}else{if(2047>=m){if(c+1>=d)break;b[c++]=192|m>>6}else{if(65535>=m){if(c+2>=d)break;b[c++]=224|m>>12}else{if(c+3>=d)break;b[c++]=240|m>>18;b[c++]=128|m>>12&63}b[c++]=128|m>>6&63}b[c++]=128|m&63}}b[c]=0;return c-f}
function y(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ia(a){for(var b="";;){var c=F(a++|0,1,1)>>>0;if(!c)return b;b+=String.fromCharCode(c)}}function fb(a){var b=y(a)+1,c=t(b);c&&z(a,I,c,b);return c}var gb,I,x,Ra,Sa,Ua,Va,Ta;
function hb(){var a=ab.buffer;gb=a;e.HEAP8=I=new Int8Array(a);e.HEAP16=Ra=new Int16Array(a);e.HEAP32=Sa=new Int32Array(a);e.HEAPU8=x=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=Ua=new Float32Array(a);e.HEAPF64=Va=new Float64Array(a);e.HEAP64=Ta=new BigInt64Array(a);e.HEAPU64=new BigUint64Array(a)}var K,ib=[],jb=[],kb=[],Xa=!1,Ya=!1;function lb(){var a=e.preRun.shift();ib.unshift(a)}var mb=0,nb=null,ob=null;e.preloadedImages={};e.preloadedAudios={};
function L(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";Na(a);bb=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function pb(){return N.startsWith("data:application/octet-stream;base64,")}var N;N="sqlmath_wasm.wasm";if(!pb()){var qb=N;N=e.locateFile?e.locateFile(qb,J):J+qb}function rb(){var a=N;try{if(a==N&&Qa)return new Uint8Array(Qa);if(Ja)return Ja(a);throw"both async and sync fetching of the wasm failed";}catch(b){L(b)}}
function sb(){if(!Qa&&(Ea||Fa)){if("function"===typeof fetch&&!N.startsWith("file://"))return fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return rb()});if(Ia)return new Promise(function(a,b){Ia(N,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return rb()})}
function tb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.dc;"number"===typeof c?void 0===b.wb?K.get(c)():K.get(c)(b.wb):c(void 0===b.wb?null:b.wb)}}}function ub(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}function vb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function O(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=vb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function wb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function xb(a){if("/"===a)return"/";a=O(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function yb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(Ga)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){L("randomDevice")}}
function zb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=vb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ab=[];function Bb(a,b){Ab[a]={input:[],output:[],nb:b};Gb(a,Ib)}
var Ib={open:function(a){var b=Ab[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.nb.flush(a.tty)},flush:function(a){a.tty.nb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.nb.Kb)throw new Q(60);for(var f=0,g=0;g<d;g++){try{var m=a.tty.nb.Kb(a.tty)}catch(q){throw new Q(29);}if(void 0===m&&0===f)throw new Q(6);if(null===m||void 0===m)break;f++;b[c+g]=m}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.nb.Ab)throw new Q(60);
try{for(var f=0;f<d;f++)a.tty.nb.Ab(a.tty,b[c+f])}catch(g){throw new Q(29);}d&&(a.node.timestamp=Date.now());return f}},Jb={Kb:function(a){if(!a.input.length){var b=null;if(Ga){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ua(b,!0)}return a.input.shift()},Ab:function(a,b){null===b||10===b?(Ma(eb(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(Ma(eb(a.output,0)),a.output=[])}},Kb={Ab:function(a,b){null===b||10===b?(Na(eb(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(Na(eb(a.output,0)),a.output=[])}};
function Lb(a){a=65536*Math.ceil(a/65536);var b=Mb(65536,a);if(!b)return 0;x.fill(0,b,b+a);return b}
var R={fb:null,gb:function(){return R.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.fb||(R.fb={dir:{node:{eb:R.Wa.eb,cb:R.Wa.cb,lookup:R.Wa.lookup,qb:R.Wa.qb,rename:R.Wa.rename,unlink:R.Wa.unlink,rmdir:R.Wa.rmdir,readdir:R.Wa.readdir,symlink:R.Wa.symlink},stream:{jb:R.Xa.jb}},file:{node:{eb:R.Wa.eb,cb:R.Wa.cb},stream:{jb:R.Xa.jb,read:R.Xa.read,write:R.Xa.write,Cb:R.Xa.Cb,rb:R.Xa.rb,sb:R.Xa.sb}},link:{node:{eb:R.Wa.eb,cb:R.Wa.cb,
readlink:R.Wa.readlink},stream:{}},Gb:{node:{eb:R.Wa.eb,cb:R.Wa.cb},stream:Nb}});c=Ob(a,b,c,d);16384===(c.mode&61440)?(c.Wa=R.fb.dir.node,c.Xa=R.fb.dir.stream,c.Ya={}):32768===(c.mode&61440)?(c.Wa=R.fb.file.node,c.Xa=R.fb.file.stream,c.bb=0,c.Ya=null):40960===(c.mode&61440)?(c.Wa=R.fb.link.node,c.Xa=R.fb.link.stream):8192===(c.mode&61440)&&(c.Wa=R.fb.Gb.node,c.Xa=R.fb.Gb.stream);c.timestamp=Date.now();a&&(a.Ya[b]=c,a.timestamp=c.timestamp);return c},ec:function(a){return a.Ya?a.Ya.subarray?a.Ya.subarray(0,
a.bb):new Uint8Array(a.Ya):new Uint8Array(0)},Hb:function(a,b){var c=a.Ya?a.Ya.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ya,a.Ya=new Uint8Array(b),0<a.bb&&a.Ya.set(c.subarray(0,a.bb),0))},ac:function(a,b){if(a.bb!=b)if(0==b)a.Ya=null,a.bb=0;else{var c=a.Ya;a.Ya=new Uint8Array(b);c&&a.Ya.set(c.subarray(0,Math.min(b,a.bb)));a.bb=b}},Wa:{eb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;
16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.bb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Qb=4096;b.blocks=Math.ceil(b.size/b.Qb);return b},cb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&R.ac(a,b.size)},lookup:function(){throw Pb[44];},qb:function(a,b,c,d){return R.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===
(a.mode&61440)){try{var d=Qb(b,c)}catch(g){}if(d)for(var f in d.Ya)throw new Q(55);}delete a.parent.Ya[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ya[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Ya[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Qb(a,b),d;for(d in c.Ya)throw new Q(55);delete a.Ya[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Ya)a.Ya.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=R.createNode(a,
b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},Xa:{read:function(a,b,c,d,f){var g=a.node.Ya;if(f>=a.node.bb)return 0;a=Math.min(a.node.bb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===I.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ya||a.Ya.subarray)){if(g)return a.Ya=b.subarray(c,c+d),a.bb=d;if(0===a.bb&&0===f)return a.Ya=
b.slice(c,c+d),a.bb=d;if(f+d<=a.bb)return a.Ya.set(b.subarray(c,c+d),f),d}R.Hb(a,f+d);if(a.Ya.subarray&&b.subarray)a.Ya.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Ya[f+g]=b[c+g];a.bb=Math.max(a.bb,f+d);return d},jb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.bb);if(0>b)throw new Q(28);return b},Cb:function(a,b,c){R.Hb(a.node,b+c);a.node.bb=Math.max(a.node.bb,b+c)},rb:function(a,b,c,d,f,g){if(0!==b)throw new Q(28);if(32768!==(a.node.mode&61440))throw new Q(43);
a=a.node.Ya;if(g&2||a.buffer!==gb){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=Lb(c);if(!c)throw new Q(48);I.set(a,c)}else d=!1,c=a.byteOffset;return{$b:c,ub:d}},sb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new Q(43);if(f&2)return 0;R.Xa.write(a,b,0,d,c,!1);return 0}}},Rb=null,Sb={},S=[],Tb=1,U=null,Ub=!0,Q=null,Pb={},V=(a,b={})=>{a=zb("/",a);if(!a)return{path:"",node:null};var c={Ib:!0,Bb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);
if(8<b.Bb)throw new Q(32);a=vb(a.split("/").filter(m=>!!m),!1);var f=Rb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Qb(f,a[d]);c=O(c+"/"+a[d]);f.lb&&(!g||g&&b.Ib)&&(f=f.lb.root);if(!g||b.ib)for(g=0;40960===(f.mode&61440);)if(f=Vb(c),c=zb(wb(c),f),f=V(c,{Bb:b.Bb}).node,40<g++)throw new Q(32);}return{path:c,node:f}},Wb=a=>{for(var b;;){if(a===a.parent)return a=a.gb.Lb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Xb=(a,b)=>{for(var c=0,d=0;d<
b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%U.length},Yb=a=>{var b=Xb(a.parent.id,a.name);if(U[b]===a)U[b]=a.mb;else for(b=U[b];b;){if(b.mb===a){b.mb=a.mb;break}b=b.mb}},Qb=(a,b)=>{var c;if(c=(c=Zb(a,"x"))?c:a.Wa.lookup?0:2)throw new Q(c,a);for(c=U[Xb(a.id,b)];c;c=c.mb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Wa.lookup(a,b)},Ob=(a,b,c,d)=>{a=new $b(a,b,c,d);b=Xb(a.parent.id,a.name);a.mb=U[b];return U[b]=a},ac={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},bc=a=>{var b=
["r","w","rw"][a&3];a&512&&(b+="w");return b},Zb=(a,b)=>{if(Ub)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},cc=(a,b)=>{try{return Qb(a,b),20}catch(c){}return Zb(a,"wx")},dc=(a,b,c)=>{try{var d=Qb(a,b)}catch(f){return f.Za}if(a=Zb(a,"wx"))return a;if(c){if(16384!==(d.mode&61440))return 54;if(d===d.parent||"/"===Wb(d))return 10}else if(16384===(d.mode&61440))return 31;return 0},ec=(a=0,b=4096)=>{for(;a<=b;a++)if(!S[a])return a;
throw new Q(33);},gc=(a,b)=>{fc||(fc=function(){},fc.prototype={});var c=new fc,d;for(d in a)c[d]=a[d];a=c;b=ec(b,void 0);a.fd=b;return S[b]=a},Nb={open:a=>{a.Xa=Sb[a.node.rdev].Xa;a.Xa.open&&a.Xa.open(a)},jb:()=>{throw new Q(70);}},Gb=(a,b)=>{Sb[a]={Xa:b}},hc=(a,b)=>{var c="/"===b,d=!b;if(c&&Rb)throw new Q(10);if(!c&&!d){var f=V(b,{Ib:!1});b=f.path;f=f.node;if(f.lb)throw new Q(10);if(16384!==(f.mode&61440))throw new Q(54);}b={type:a,fc:{},Lb:b,Yb:[]};a=a.gb(b);a.gb=b;b.root=a;c?Rb=a:f&&(f.lb=b,f.gb&&
f.gb.Yb.push(b))},ic=(a,b,c)=>{var d=V(a,{parent:!0}).node;a=xb(a);if(!a||"."===a||".."===a)throw new Q(28);var f=cc(d,a);if(f)throw new Q(f);if(!d.Wa.qb)throw new Q(63);return d.Wa.qb(d,a,b,c)},W=(a,b)=>ic(a,(void 0!==b?b:511)&1023|16384,0),jc=(a,b,c)=>{"undefined"===typeof c&&(c=b,b=438);ic(a,b|8192,c)},kc=(a,b)=>{if(!zb(a))throw new Q(44);var c=V(b,{parent:!0}).node;if(!c)throw new Q(44);b=xb(b);var d=cc(c,b);if(d)throw new Q(d);if(!c.Wa.symlink)throw new Q(63);c.Wa.symlink(c,b,a)},la=a=>{var b=
V(a,{parent:!0}).node;if(!b)throw new Q(44);a=xb(a);var c=Qb(b,a),d=dc(b,a,!1);if(d)throw new Q(d);if(!b.Wa.unlink)throw new Q(63);if(c.lb)throw new Q(10);b.Wa.unlink(b,a);Yb(c)},Vb=a=>{a=V(a).node;if(!a)throw new Q(44);if(!a.Wa.readlink)throw new Q(28);return zb(Wb(a.parent),a.Wa.readlink(a))},lc=(a,b)=>{a=V(a,{ib:!b}).node;if(!a)throw new Q(44);if(!a.Wa.eb)throw new Q(63);return a.Wa.eb(a)},mc=a=>lc(a,!0),nc=(a,b)=>{a="string"===typeof a?V(a,{ib:!0}).node:a;if(!a.Wa.cb)throw new Q(63);a.Wa.cb(a,
{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},oc=a=>{a="string"===typeof a?V(a,{ib:!0}).node:a;if(!a.Wa.cb)throw new Q(63);a.Wa.cb(a,{timestamp:Date.now()})},pc=(a,b)=>{if(0>b)throw new Q(28);a="string"===typeof a?V(a,{ib:!0}).node:a;if(!a.Wa.cb)throw new Q(63);if(16384===(a.mode&61440))throw new Q(31);if(32768!==(a.mode&61440))throw new Q(28);var c=Zb(a,"w");if(c)throw new Q(c);a.Wa.cb(a,{size:b,timestamp:Date.now()})},rc=(a,b,c,d)=>{if(""===a)throw new Q(44);if("string"===typeof b){var f=ac[b];
if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=O(a);try{g=V(a,{ib:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(g){if(b&128)throw new Q(20);}else g=ic(a,c,0),f=!0;if(!g)throw new Q(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new Q(54);if(!f&&(c=g?40960===(g.mode&61440)?32:16384===(g.mode&61440)&&("r"!==bc(b)||b&512)?31:Zb(g,bc(b)):44))throw new Q(c);b&
512&&pc(g,0);b&=-131713;d=gc({node:g,path:Wb(g),flags:b,seekable:!0,position:0,Xa:g.Xa,cc:[],error:!1},d);d.Xa.open&&d.Xa.open(d);!e.logReadFiles||b&1||(qc||(qc={}),a in qc||(qc[a]=1));return d},sc=a=>{if(null===a.fd)throw new Q(8);a.yb&&(a.yb=null);try{a.Xa.close&&a.Xa.close(a)}catch(b){throw b;}finally{S[a.fd]=null}a.fd=null},tc=(a,b,c)=>{if(null===a.fd)throw new Q(8);if(!a.seekable||!a.Xa.jb)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.Xa.jb(a,b,c);a.cc=[]},uc=(a,b,c,d,f)=>
{if(0>d||0>f)throw new Q(28);if(null===a.fd)throw new Q(8);if(1===(a.flags&2097155))throw new Q(8);if(16384===(a.node.mode&61440))throw new Q(31);if(!a.Xa.read)throw new Q(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new Q(70);b=a.Xa.read(a,b,c,d,f);g||(a.position+=b);return b},vc=(a,b,c,d,f)=>{var g=void 0;if(0>d||0>g)throw new Q(28);if(null===a.fd)throw new Q(8);if(0===(a.flags&2097155))throw new Q(8);if(16384===(a.node.mode&61440))throw new Q(31);if(!a.Xa.write)throw new Q(28);
a.seekable&&a.flags&1024&&tc(a,0,2);var m="undefined"!==typeof g;if(!m)g=a.position;else if(!a.seekable)throw new Q(70);b=a.Xa.write(a,b,c,d,g,f);m||(a.position+=b);return b},Aa=a=>{var b="binary";if("utf8"!==b&&"binary"!==b)throw Error('Invalid encoding type "'+b+'"');var c;var d=rc(a,d||0);a=lc(a).size;var f=new Uint8Array(a);uc(d,f,0,a,0);"utf8"===b?c=eb(f,0):"binary"===b&&(c=f);sc(d);return c},ja=(a,b)=>{var c={};c.flags=c.flags||577;a=rc(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(y(b)+
1);b=z(b,d,0,d.length);vc(a,d,0,b,c.Sb)}else if(ArrayBuffer.isView(b))vc(a,b,0,b.byteLength,c.Sb);else throw Error("Unsupported data type");sc(a)},Vc=()=>{Q||(Q=function(a,b){this.node=b;this.bc=function(c){this.Za=c};this.bc(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(a=>{Pb[a]=new Q(a);Pb[a].stack="<generic error, no stack>"}))},Wc,Xc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Zc=(a,b,c)=>{a=O("/dev/"+a);var d=Xc(!!b,!!c);Yc||(Yc=64);var f=Yc++<<
8|0;Gb(f,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,m,q,r)=>{for(var p=0,w=0;w<r;w++){try{var H=b()}catch(Z){throw new Q(29);}if(void 0===H&&0===p)throw new Q(6);if(null===H||void 0===H)break;p++;m[q+w]=H}p&&(g.node.timestamp=Date.now());return p},write:(g,m,q,r)=>{for(var p=0;p<r;p++)try{c(m[q+p])}catch(w){throw new Q(29);}r&&(g.node.timestamp=Date.now());return p}});jc(a,d,f)},Yc,X={},fc,qc,$c={};
function ad(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&O(b)!==O(Wb(f.node)))return-54;throw f;}M(c|0,d.dev|0,4);M(c+4|0,0,4);M(c+8|0,d.ino|0,4);M(c+12|0,d.mode|0,4);M(c+16|0,d.nlink|0,4);M(c+20|0,d.uid|0,4);M(c+24|0,d.gid|0,4);M(c+28|0,d.rdev|0,4);M(c+32|0,0,4);M(c+40|0,d.size|0,8);M(c+48|0,4096,4);M(c+52|0,d.blocks|0,4);M(c+56|0,d.atime.getTime()/1E3|0,4);M(c+60|0,0,4);M(c+64|0,d.mtime.getTime()/1E3|0,4);M(c+68|0,0,4);M(c+72|0,d.ctime.getTime()/1E3|0,4);M(c+76|0,0,4);M(c+80|0,d.ino|0,8);return 0}
var bd=void 0;function cd(){bd+=4;return F(bd-4|0,4,0)|0}function Y(a){a=S[a];if(!a)throw new Q(8);return a}function dd(a,b,c){function d(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}var f=(new Date).getFullYear(),g=new Date(f,0,1),m=new Date(f,6,1);f=g.getTimezoneOffset();var q=m.getTimezoneOffset();M(a|0,60*Math.max(f,q)|0,4);M(b|0,Number(f!=q)|0,4);a=d(g);b=d(m);a=fb(a);b=fb(b);q<f?(M(c|0,a|0,4),M(c+4|0,b|0,4)):(M(c|0,b|0,4),M(c+4|0,a|0,4))}
function ed(a,b,c){ed.Rb||(ed.Rb=!0,dd(a,b,c))}var fd;fd=Ga?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var gd={};function hd(){if(!jd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:Da||"./this.program"},b;for(b in gd)void 0===gd[b]?delete a[b]:a[b]=gd[b];var c=[];for(b in a)c.push(b+"="+a[b]);jd=c}return jd}var jd;
function $b(a,b,c,d){a||(a=this);this.parent=a;this.gb=a.gb;this.lb=null;this.id=Tb++;this.name=b;this.mode=c;this.Wa={};this.Xa={};this.rdev=d}Object.defineProperties($b.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Vc();U=Array(4096);hc(R,"/");W("/tmp");W("/home");W("/home/web_user");
(()=>{W("/dev");Gb(259,{read:()=>0,write:(b,c,d,f)=>f});jc("/dev/null",259);Bb(1280,Jb);Bb(1536,Kb);jc("/dev/tty",1280);jc("/dev/tty1",1536);var a=yb();Zc("random",a);Zc("urandom",a);W("/dev/shm");W("/dev/shm/tmp")})();(()=>{W("/proc");var a=W("/proc/self");W("/proc/self/fd");hc({gb:()=>{var b=Ob(a,"fd",16895,73);b.Wa={lookup:(c,d)=>{var f=S[+d];if(!f)throw new Q(8);c={parent:null,gb:{Lb:"fake"},Wa:{readlink:()=>f.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
function ua(a,b){var c=Array(y(a)+1);a=z(a,c,0,c.length);b&&(c.length=a);return c}
var ld={b:function(a,b,c,d){L("Assertion failed: "+G(a)+", at: "+[b?G(b):"unknown filename",c,d?G(d):"unknown function"])},m:function(a,b){try{a=G(a);if(b&-8)var c=-28;else{var d=V(a,{ib:!0}).node;d?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&Zb(d,a)?-2:0):c=-44}return c}catch(f){if("undefined"===typeof X||!(f instanceof Q))throw f;return-f.Za}},O:function(a,b){try{return a=G(a),nc(a,b),0}catch(c){if("undefined"===typeof X||!(c instanceof Q))throw c;return-c.Za}},M:function(a){try{return a=
G(a),oc(a),0}catch(b){if("undefined"===typeof X||!(b instanceof Q))throw b;return-b.Za}},k:function(a,b){try{var c=S[a];if(!c)throw new Q(8);nc(c.node,b);return 0}catch(d){if("undefined"===typeof X||!(d instanceof Q))throw d;return-d.Za}},N:function(a){try{var b=S[a];if(!b)throw new Q(8);oc(b.node);return 0}catch(c){if("undefined"===typeof X||!(c instanceof Q))throw c;return-c.Za}},d:function(a,b,c){bd=c;try{var d=Y(a);switch(b){case 0:var f=cd();return 0>f?-28:rc(d.path,d.flags,0,f).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return f=cd(),d.flags|=f,0;case 5:return f=cd(),M(f+0|0,2,2),0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return M(kd()|0,28,4),-1;default:return-28}}catch(g){if("undefined"===typeof X||!(g instanceof Q))throw g;return-g.Za}},K:function(a,b){try{var c=Y(a);return ad(lc,c.path,b)}catch(d){if("undefined"===typeof X||!(d instanceof Q))throw d;return-d.Za}},H:function(a,b,c,d){try{b=G(b);var f=d&256;d&=4096;var g=b;if("/"===g[0])b=g;else{if(-100===a)var m="/";
else{var q=S[a];if(!q)throw new Q(8);m=q.path}if(0==g.length){if(!d)throw new Q(44);b=m}else b=O(m+"/"+g)}return ad(f?mc:lc,b,c)}catch(r){if("undefined"===typeof X||!(r instanceof Q))throw r;return-r.Za}},E:function(a,b){try{var c=S[a];if(!c)throw new Q(8);if(0===(c.flags&2097155))throw new Q(28);pc(c.node,b);return 0}catch(d){if("undefined"===typeof X||!(d instanceof Q))throw d;return-d.Za}},D:function(a,b){try{if(0===b)return-28;if(b<y("/")+1)return-68;z("/",x,a,b);return a}catch(c){if("undefined"===
typeof X||!(c instanceof Q))throw c;return-c.Za}},A:function(){return 0},L:function(a,b,c){bd=c;try{var d=Y(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=cd();M(f|0,0,4);return 0;case 21520:return d.tty?-28:-59;case 21531:a=f=cd();if(!d.Xa.Vb)throw new Q(59);return d.Xa.Vb(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:L("bad ioctl syscall "+
b)}}catch(g){if("undefined"===typeof X||!(g instanceof Q))throw g;return-g.Za}},G:function(a,b){try{return a=G(a),ad(mc,a,b)}catch(c){if("undefined"===typeof X||!(c instanceof Q))throw c;return-c.Za}},w:function(a,b){try{return a=G(a),a=O(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),W(a,b),0}catch(c){if("undefined"===typeof X||!(c instanceof Q))throw c;return-c.Za}},v:function(a,b,c,d,f,g){try{a:{g<<=12;var m=!1;if(0!==(d&16)&&0!==a%65536)var q=-28;else{if(0!==(d&32)){var r=Lb(b);if(!r){q=-48;
break a}m=!0}else{var p=S[f];if(!p){q=-8;break a}var w=g;if(0!==(c&2)&&0===(d&2)&&2!==(p.flags&2097155))throw new Q(2);if(1===(p.flags&2097155))throw new Q(2);if(!p.Xa.rb)throw new Q(43);var H=p.Xa.rb(p,a,b,w,c,d);r=H.$b;m=H.ub}$c[r]={Xb:r,Wb:b,ub:m,fd:f,Zb:c,flags:d,offset:g};q=r}}return q}catch(Z){if("undefined"===typeof X||!(Z instanceof Q))throw Z;return-Z.Za}},u:function(a,b){try{var c=$c[a];if(0!==b&&c){if(b===c.Wb){var d=S[c.fd];if(d&&c.Zb&2){var f=c.flags,g=c.offset,m=x.slice(a,a+b);d&&d.Xa.sb&&
d.Xa.sb(d,m,g,b,f)}$c[a]=null;c.ub&&ma(c.Xb)}var q=0}else q=-28;return q}catch(r){if("undefined"===typeof X||!(r instanceof Q))throw r;return-r.Za}},j:function(a,b,c){bd=c;try{var d=G(a),f=c?cd():0;return rc(d,b,f).fd}catch(g){if("undefined"===typeof X||!(g instanceof Q))throw g;return-g.Za}},t:function(a,b,c){try{a=G(a);if(0>=c)var d=-28;else{var f=Vb(a),g=Math.min(c,y(f)),m=F(b+g,1,0);z(f,x,b,c+1);M(b+g,m,1);d=g}return d}catch(q){if("undefined"===typeof X||!(q instanceof Q))throw q;return-q.Za}},
s:function(a){try{a=G(a);var b=V(a,{parent:!0}).node,c=xb(a),d=Qb(b,c),f=dc(b,c,!0);if(f)throw new Q(f);if(!b.Wa.rmdir)throw new Q(63);if(d.lb)throw new Q(10);b.Wa.rmdir(b,c);Yb(d);return 0}catch(g){if("undefined"===typeof X||!(g instanceof Q))throw g;return-g.Za}},J:function(a,b){try{return a=G(a),ad(lc,a,b)}catch(c){if("undefined"===typeof X||!(c instanceof Q))throw c;return-c.Za}},q:function(a){try{return a=G(a),la(a),0}catch(b){if("undefined"===typeof X||!(b instanceof Q))throw b;return-b.Za}},
g:function(){L("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},l:function(){L("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},y:function(a,b){a=new Date(1E3*(F(a|0,4,0)|0));M(b|0,a.getSeconds()|0,4);M(b+4|0,a.getMinutes()|0,4);M(b+8|0,a.getHours()|0,4);M(b+12|0,a.getDate()|0,4);M(b+16|0,a.getMonth()|0,4);M(b+20|0,a.getFullYear()-1900|0,4);
M(b+24|0,a.getDay()|0,4);var c=new Date(a.getFullYear(),0,1);M(b+28|0,(a.getTime()-c.getTime())/864E5|0,4);M(b+36|0,-(60*a.getTimezoneOffset())|0,4);var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();M(b+32|0,(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0,4)},z:ed,o:function(){L("")},c:function(){L("alignment fault")},r:function(){return 2147483648},h:fd,n:function(a){var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ab.grow(Math.min(2147483648,d)-gb.byteLength+65535>>>16);hb();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},B:function(a,b){var c=0;hd().forEach(function(d,f){var g=b+c;M(a+4*f|0,g|0,4);f=g;for(g=0;g<d.length;++g)M(f++|0,d.charCodeAt(g)|0,1);M(f|0,0,1);c+=d.length+1});return 0},C:function(a,b){var c=hd();M(a|0,c.length|0,4);var d=0;c.forEach(function(f){d+=f.length+1});M(b|0,d|0,4);return 0},e:function(a){try{var b=Y(a);
sc(b);return 0}catch(c){if("undefined"===typeof X||!(c instanceof Q))throw c;return c.Za}},p:function(a,b){try{var c=Y(a);M(b|0,(c.tty?2:16384===(c.mode&61440)?3:40960===(c.mode&61440)?7:4)|0,1);return 0}catch(d){if("undefined"===typeof X||!(d instanceof Q))throw d;return d.Za}},i:function(a,b,c,d){try{a:{for(var f=Y(a),g=a=0;g<c;g++){var m=F(b+8*g|0,4,0)|0,q=F(b+(8*g+4)|0,4,0)|0,r=uc(f,I,m,q,void 0);if(0>r){var p=-1;break a}a+=r;if(r<q)break}p=a}M(d|0,p|0,4);return 0}catch(w){if("undefined"===typeof X||
!(w instanceof Q))throw w;return w.Za}},x:function(a,b,c,d){try{var f=Number(b&BigInt(4294967295))|0,g=Number(b>>BigInt(32))|0,m=Y(a);a=4294967296*g+(f>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;tc(m,a,c);M(d|0,m.position|0,8);m.yb&&0===a&&0===c&&(m.yb=null);return 0}catch(q){if("undefined"===typeof X||!(q instanceof Q))throw q;return q.Za}},F:function(a){try{var b=Y(a);return b.Xa&&b.Xa.fsync?-b.Xa.fsync(b):0}catch(c){if("undefined"===typeof X||!(c instanceof Q))throw c;return c.Za}},
f:function(a,b,c,d){try{a:{for(var f=Y(a),g=a=0;g<c;g++){var m=F(b+8*g|0,4,0)|0,q=F(b+(8*g+4)|0,4,0)|0,r=vc(f,I,m,q);if(0>r){var p=-1;break a}a+=r}p=a}M(d|0,p|0,4);return 0}catch(w){if("undefined"===typeof X||!(w instanceof Q))throw w;return w.Za}},I:function(a){var b=Date.now();M(a|0,b/1E3|0,4);M(a+4|0,b%1E3*1E3|0,4);return 0},a:function(){L("segmentation fault")},P:function(a){var b=Date.now()/1E3|0;a&&M(a|0,b|0,4);return b},Q:function(a,b){if(b){var c=b+8;b=1E3*(F(c|0,4,0)|0);b+=(F(c+4|0,4,0)|
0)/1E3}else b=Date.now();a=G(a);try{var d=V(a,{ib:!0}).node;d.Wa.cb(d,{timestamp:Math.max(b,b)});var f=0}catch(g){if(!(g instanceof Q)){b:{f=Error();if(!f.stack){try{throw Error();}catch(m){f=m}if(!f.stack){f="(no stack trace available)";break b}}f=f.stack.toString()}e.extraStackTrace&&(f+="\n"+e.extraStackTrace());f=ub(f);throw g+" : "+f;}f=g.Za;M(kd()|0,f|0,4);f=-1}return f}};
(function(){function a(f){e.asm=f.exports;ab=e.asm.R;hb();K=e.asm.Pa;jb.unshift(e.asm.S);mb--;e.monitorRunDependencies&&e.monitorRunDependencies(mb);0==mb&&(null!==nb&&(clearInterval(nb),nb=null),ob&&(f=ob,ob=null,f()))}function b(f){a(f.instance)}function c(f){return sb().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(f,function(g){Na("failed to asynchronously prepare wasm: "+g);L(g)})}var d={a:ld};mb++;e.monitorRunDependencies&&e.monitorRunDependencies(mb);
if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return Na("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Qa||"function"!==typeof WebAssembly.instantiateStreaming||pb()||N.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){Na("wasm streaming compile failed: "+g);Na("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.S).apply(null,arguments)};e._sqlite3_free=function(){return(e._sqlite3_free=e.asm.T).apply(null,arguments)};e._sqlite3_prepare_v2=function(){return(e._sqlite3_prepare_v2=e.asm.U).apply(null,arguments)};e._sqlite3_step=function(){return(e._sqlite3_step=e.asm.V).apply(null,arguments)};e._sqlite3_finalize=function(){return(e._sqlite3_finalize=e.asm.W).apply(null,arguments)};
e._sqlite3_reset=function(){return(e._sqlite3_reset=e.asm.X).apply(null,arguments)};e._sqlite3_clear_bindings=function(){return(e._sqlite3_clear_bindings=e.asm.Y).apply(null,arguments)};e._sqlite3_value_blob=function(){return(e._sqlite3_value_blob=e.asm.Z).apply(null,arguments)};e._sqlite3_value_text=function(){return(e._sqlite3_value_text=e.asm._).apply(null,arguments)};e._sqlite3_value_bytes=function(){return(e._sqlite3_value_bytes=e.asm.$).apply(null,arguments)};
e._sqlite3_value_double=function(){return(e._sqlite3_value_double=e.asm.aa).apply(null,arguments)};e._sqlite3_value_int=function(){return(e._sqlite3_value_int=e.asm.ba).apply(null,arguments)};e._sqlite3_value_type=function(){return(e._sqlite3_value_type=e.asm.ca).apply(null,arguments)};e._sqlite3_result_blob=function(){return(e._sqlite3_result_blob=e.asm.da).apply(null,arguments)};e._sqlite3_result_double=function(){return(e._sqlite3_result_double=e.asm.ea).apply(null,arguments)};
e._sqlite3_result_error=function(){return(e._sqlite3_result_error=e.asm.fa).apply(null,arguments)};e._sqlite3_result_int=function(){return(e._sqlite3_result_int=e.asm.ga).apply(null,arguments)};e._sqlite3_result_int64=function(){return(e._sqlite3_result_int64=e.asm.ha).apply(null,arguments)};e._sqlite3_result_null=function(){return(e._sqlite3_result_null=e.asm.ia).apply(null,arguments)};e._sqlite3_result_text=function(){return(e._sqlite3_result_text=e.asm.ja).apply(null,arguments)};
e._sqlite3_column_count=function(){return(e._sqlite3_column_count=e.asm.ka).apply(null,arguments)};e._sqlite3_data_count=function(){return(e._sqlite3_data_count=e.asm.la).apply(null,arguments)};e._sqlite3_column_blob=function(){return(e._sqlite3_column_blob=e.asm.ma).apply(null,arguments)};e._sqlite3_column_bytes=function(){return(e._sqlite3_column_bytes=e.asm.na).apply(null,arguments)};e._sqlite3_column_double=function(){return(e._sqlite3_column_double=e.asm.oa).apply(null,arguments)};
e._sqlite3_column_text=function(){return(e._sqlite3_column_text=e.asm.pa).apply(null,arguments)};e._sqlite3_column_type=function(){return(e._sqlite3_column_type=e.asm.qa).apply(null,arguments)};e._sqlite3_column_name=function(){return(e._sqlite3_column_name=e.asm.ra).apply(null,arguments)};e._sqlite3_bind_blob=function(){return(e._sqlite3_bind_blob=e.asm.sa).apply(null,arguments)};e._sqlite3_bind_double=function(){return(e._sqlite3_bind_double=e.asm.ta).apply(null,arguments)};
e._sqlite3_bind_int=function(){return(e._sqlite3_bind_int=e.asm.ua).apply(null,arguments)};e._sqlite3_bind_text=function(){return(e._sqlite3_bind_text=e.asm.va).apply(null,arguments)};e._sqlite3_bind_parameter_index=function(){return(e._sqlite3_bind_parameter_index=e.asm.wa).apply(null,arguments)};e._sqlite3_sql=function(){return(e._sqlite3_sql=e.asm.xa).apply(null,arguments)};e._sqlite3_normalized_sql=function(){return(e._sqlite3_normalized_sql=e.asm.ya).apply(null,arguments)};
e._sqlite3_exec=function(){return(e._sqlite3_exec=e.asm.za).apply(null,arguments)};e._sqlite3_errmsg=function(){return(e._sqlite3_errmsg=e.asm.Aa).apply(null,arguments)};e._sqlite3_changes=function(){return(e._sqlite3_changes=e.asm.Ba).apply(null,arguments)};e._sqlite3_close_v2=function(){return(e._sqlite3_close_v2=e.asm.Ca).apply(null,arguments)};e._sqlite3_create_function_v2=function(){return(e._sqlite3_create_function_v2=e.asm.Da).apply(null,arguments)};
e._sqlite3_open=function(){return(e._sqlite3_open=e.asm.Ea).apply(null,arguments)};
var ma=e._free=function(){return(ma=e._free=e.asm.Fa).apply(null,arguments)},t=e._malloc=function(){return(t=e._malloc=e.asm.Ga).apply(null,arguments)},kd=e.___errno_location=function(){return(kd=e.___errno_location=e.asm.Ha).apply(null,arguments)},ka=e.___dbMemoryLoadOrSave=function(){return(ka=e.___dbMemoryLoadOrSave=e.asm.Ia).apply(null,arguments)},na=e._dbClose=function(){return(na=e._dbClose=e.asm.Ja).apply(null,arguments)},pa=e._dbExec=function(){return(pa=e._dbExec=e.asm.Ka).apply(null,arguments)},
qa=e._dbMemoryLoadOrSave=function(){return(qa=e._dbMemoryLoadOrSave=e.asm.La).apply(null,arguments)},ra=e._dbNoop=function(){return(ra=e._dbNoop=e.asm.Ma).apply(null,arguments)},sa=e._dbOpen=function(){return(sa=e._dbOpen=e.asm.Na).apply(null,arguments)},ta=e._dbTableInsert=function(){return(ta=e._dbTableInsert=e.asm.Oa).apply(null,arguments)},Za=e._sbrk=function(){return(Za=e._sbrk=e.asm.Qa).apply(null,arguments)},Mb=e._memalign=function(){return(Mb=e._memalign=e.asm.Ra).apply(null,arguments)},$a=
e._emscripten_stack_get_base=function(){return($a=e._emscripten_stack_get_base=e.asm.Sa).apply(null,arguments)},wa=e.stackSave=function(){return(wa=e.stackSave=e.asm.Ta).apply(null,arguments)},ya=e.stackRestore=function(){return(ya=e.stackRestore=e.asm.Ua).apply(null,arguments)},E=e.stackAlloc=function(){return(E=e.stackAlloc=e.asm.Va).apply(null,arguments)};e.cwrap=da;e.UTF8ToString=G;e.stackSave=wa;e.stackRestore=ya;e.stackAlloc=E;var md;ob=function nd(){md||od();md||(ob=nd)};
function od(){function a(){if(!md&&(md=!0,e.calledRun=!0,!bb)){Xa=!0;e.noFSInit||Wc||(Wc=!0,Vc(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?Zc("stdin",e.stdin):kc("/dev/tty","/dev/stdin"),e.stdout?Zc("stdout",null,e.stdout):kc("/dev/tty","/dev/stdout"),e.stderr?Zc("stderr",null,e.stderr):kc("/dev/tty1","/dev/stderr"),rc("/dev/stdin",0),rc("/dev/stdout",1),rc("/dev/stderr",1));Ub=!1;tb(jb);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&
(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();kb.unshift(b)}tb(kb)}}if(!(0<mb)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)lb();tb(ib);0<mb||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=od;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();od();

}());
/*jslint-enable*/
